### ISSUE TITLE
More information about the 12/15 meeting?

### ISSUE THREAD

**Issue by bsweger** [usgpo/bill-status#1]
Hello! Saw the note on your README about the meeting on 12/15. When I called the listed number, those folks didn't know about this event. Do you have more details (specifically, is there a remote participation option)? 

Thanks for any information.

**Comment by llaplant** [comment]
The Legislative Branch Bulk Data Task Force Technical Presentation will take place in the Legislative Resource Center (LRC) Conference Room in the Cannon House Office Building near room 133 from 1:00 to 2:20 PM on Tuesday, December 15, 2015. Unfortunately, a remote participation option will not be available, but a video of the meeting and meeting slides will be made available after the meeting.

**Comment by bsweger** [comment]
Thanks for the update--much appreciated!
