### ISSUE TITLE
Latest House Bills missing information

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#100]
The latest House Bills introduced 5/29 (HR5984-HR5987) are missing sponsor and title information

https://www.congress.gov/bill/115th-congress/house-bill/5984
https://www.congress.gov/bill/115th-congress/house-bill/5985
https://www.congress.gov/bill/115th-congress/house-bill/5986
https://www.congress.gov/bill/115th-congress/house-bill/5987

**Comment by 104PL104** [comment]
Thank you for reporting this. It is also an issue in Congress.gov. We'll get this corrected at the source, then will circle back.

**Comment by kboyd35** [comment]
It looks like these bills have been updated in https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/hr

There are 267 bills updated with a timestamp of 5-31 but none are updated in the sitemap.

https://www.gpo.gov/smap/bulkdata/BILLSTATUS/115hr/sitemap.xml

**Comment by jzheng-gpo** [comment]
The sitemap is updated now. Got 4423 hit with 2018-05-31.
