### ISSUE TITLE
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s2979.xml is empty

### ISSUE THREAD

**Issue by AmitElhanan** [usgpo/bill-status#103]
A link exists on govinfo.gov but there is no data in the file

**Comment by jzheng-gpo** [comment]
Will republish it and let you know. They are under refreshing now.

**Comment by jzheng-gpo** [comment]
Republished now.

**Comment by llaplant** [comment]
Verified at https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s2979.xml and closing.
