### ISSUE TITLE
Introduced Senate bills from 7/26 are on congress.gov but are not available in the bill status feed 

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#106]
Senate Bill 3288 through 3291 and 2393-3295 are available on congress.gov, but are not available in the bill 
status feed.

For example:
https://www.congress.gov/bill/115th-congress/senate-bill/3295

**Comment by jzheng-gpo** [comment]
api.data.gov is not updated yet.

**Comment by jzheng-gpo** [comment]
Under refreshing now and will update you once available.

**Comment by jzheng-gpo** [comment]
Above Senate Bills is published in bulkdata now and is not in RSS feed yet, which might take one or two hours for this batch to complete.

**Comment by kboyd35** [comment]
Thanks.
