### ISSUE TITLE
HR 5515 and HR 6147 have actions from 8/1 on congress.gov but not in bill status xml

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#107]
Can you please let us know when the feed will be updated.

**Comment by jzheng-gpo** [comment]
Will force an update on those large files which might take couple of hours.

**Comment by wcarter** [comment]
Thank you!

**Comment by jzheng-gpo** [comment]
Only below might be skipped for updating today. Will run update on all of them:
BILLSTATUS-115hr2810, BILLSTATUS-115hr5515, BILLSTATUS-115hr6147, BILLSTATUS-115hconres71 , BILLSTATUS-115hr2

**Comment by wcarter** [comment]
great.

**Comment by jzheng-gpo** [comment]
Refreshed and the actions 2018-08-01 shows up on both bills now.

**Comment by llaplant** [comment]
BILLSTATUS-115hr5515 is currently being processed, and due to its size, is anticipated to take around 2 hours to complete.

**Comment by jzheng-gpo** [comment]
The HR 5515 is updated now.
