### ISSUE TITLE
Bills on Congress.gov are not available in bill status feed

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#108]
For example:
https://www.congress.gov/bill/115th-congress/house-bill/6690

**Comment by jzheng-gpo** [comment]
The updating job is running. Will monitor it.

**Comment by jzheng-gpo** [comment]
The new bills 6682-6690 is published now and might not be in RSS yet.

**Comment by wcarter** [comment]
There is a delay today 9/6/2018.  For example HR 6712 is available on congress.gov but is not in the bill status feed.  I don't see any updates this morning.

**Comment by jzheng-gpo** [comment]
Kicking off the job manually now. Will update you once complete.

**Comment by jzheng-gpo** [comment]
Those bills (hr6702 - 12, hres 1050-51, and s3408-11) are published now and might not be in RSS yet.
