### ISSUE TITLE
Introduced Senate bills from 9/19 are on congress.gov but are not available in the bill status feed

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#110]
Example: 
https://www.congress.gov/bill/115th-congress/senate-bill/3479

**Comment by gpo-billstatus** [comment]
There is a large amount of data update from LOC data feed, it is under processing now.

**Comment by jzheng-gpo** [comment]
See another around full refresh and will update if the new senate bills are included shortly.
