### ISSUE TITLE
S. 1595 is missing latest actions

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#111]
Hi,

S. 1595 was enacted on Oct 25:

https://www.congress.gov/bill/115th-congress/senate-bill/1595

but the bulk data's last action was on Oct 12 (`Message on Senate action sent to the House.`):

https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1595.xml

**Comment by jzheng-gpo** [comment]
Republished and it is updated now. Please review.

**Comment by JoshData** [comment]
Looks good, thanks!
