### ISSUE TITLE
Incorrect House Report Document (H. Rept. 115-999)

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#112]
Good afternoon,

Apologies if this is the incorrect collection to enter in the issue--but the committee report for H. Rept. 115-999 is incorrectly linking to a House Appropriations Committee report from May 2018: https://www.congress.gov/congressional-report/115th-congress/house-report/999/1?r=1

It looks like govinfo.gov published the Appropriations Committee version, but then added the correct Natural Resources Committee report for H.R. 3117, but the date is still 5/24/2018 instead of 11/02/2018 as written in the text of the report: https://www.govinfo.gov/app/collection/crpt/115/hrpt

Would you be able to correct? Thank you!

**Comment by llaplant** [comment]
@anerbovig could you check if this is still an open issue?

Congress.gov lists Natural Resources Committee at 
https://www.congress.gov/congressional-report/115th-congress/house-report/999/1?r=1

The date of 11/02/2018 is extracted from the date on the first page of the report which is "November 2, 2018. -- Ordered to be printed"
https://www.govinfo.gov/content/pkg/CRPT-115hrpt999/html/CRPT-115hrpt999-pt1.htm

This date is reflected in MODS metadata as `<dateIssued>`
https://www.govinfo.gov/metadata/pkg/CRPT-115hrpt999/mods.xml
https://www.govinfo.gov/app/details/CRPT-115hrpt999/CRPT-115hrpt999-pt1

Thanks!

**Comment by anerbovig** [comment]
Hi Lisa, yes, this is all corrected--thank you for following up!
