### ISSUE TITLE
Can you provide 116th Congress bills ETA

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#114]
It would be helpful to know when we can expect to see the resolutions introduced yesterday.

**Comment by jzheng-gpo** [comment]
Just checked and saw no update from LOC site yet. Will follow up.

**Comment by wcarter** [comment]
I see they are on congress.gov now.

**Comment by jzheng-gpo** [comment]
LOC is working on resolving the service availability issue.

**Comment by jzheng-gpo** [comment]
The sites https://www.govinfo.gov/bulkdata/BILLSTATUS/116 are updated now.

**Comment by llaplant** [comment]
The 116th Congress job runs at 4, 8, and 12 every 4 hours. The 115th Congress job runs at 6, 10, and 2 every 4 hours. The 114th Congress job runs at 2 daily.
