### ISSUE TITLE
Susan Wild still has old district in cosponsor information in bill status for HR51 -- 15 not 7

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#115]
<item>
        <district>15</district>
        <fullName>Rep. Wild, Susan [D-PA-15]</fullName>
        <identifiers>
          <bioguideId>W000826</bioguideId>
          <gpoId />
          <lisID>2374</lisID>
        </identifiers>
        <isOriginalCosponsor>True</isOriginalCosponsor>
        <sponsorshipDate>2019-01-03</sponsorshipDate>
        <sponsorshipWithdrawnDate />
        <party>D</party>
        <state>PA</state>
        <middleName />
        <bioguideId>W000826</bioguideId>
        <lastName>Wild</lastName>
        <firstName>Susan</firstName>
      </item>

**Comment by llaplant** [comment]
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr51.xml
Updated. Please verify.

**Comment by llaplant** [comment]
Updated with `<fullName>Rep. Wild, Susan [D-PA-7]</fullName>`. 
See link above.
