### ISSUE TITLE
Related bills linking to wrong congress

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#116]
S1 is related to HR 31 in 115th congress whenI it logically should be HR 31 in 116th

    <relatedBills>
      <item>
        <latestAction>
          <actionDate>2017-01-03</actionDate>
          <text>Referred to the House Committee on Oversight and Government Reform.</text>
        </latestAction>
        <type>HR</type>
        <relationshipDetails>
          <item>
            <identifiedBy>CRS</identifiedBy>
            <type>Related bill</type>
          </item>
        </relationshipDetails>
        <congress>115</congress>
        <number>31</number>
        <latestTitle>Federal Sunset Act of 2017</latestTitle>
      </item>
    </relatedBills>

https://www.congress.gov/bill/116th-congress/senate-bill/1/related-bills?

**Comment by adk2009** [comment]
Thanks for reporting. LOC/CRS is investigating.

**Comment by 104PL104** [comment]
This has been corrected at the source. Thanks.

**Comment by jzheng-gpo** [comment]
Updated now:
<relatedBills>
<item>
<congress>116</congress>
<latestAction>
<text>
Referred to the Committee on Foreign Affairs, and in addition to the Committees on Financial Services, and the Judiciary, for a period to be subsequently determined by the Speaker, in each case for consideration of such provisions as fall within the jurisdiction of the committee concerned.
</text>
<actionDate>2019-01-03</actionDate>
</latestAction>
<number>31</number>
<type>HR</type>
<relationshipDetails>
<item>
<type>Related bill</type>
<identifiedBy>CRS</identifiedBy>
</item>
</relationshipDetails>
<latestTitle>Caesar Syria Civilian Protection Act of 2019</latestTitle>
</item>
</relatedBills>
