### ISSUE TITLE
S. 440 and S. 441 Missing from Bill Status Bulk Data

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#118]
Good afternoon, all of the introduced bills from yesterday are available on the govinfo.gov bulk data site, except for S. 440 and S. 441: https://www.govinfo.gov/bulkdata/BILLSTATUS/116/s

Do you know if these will be up later today? Thank you!

**Comment by jzheng-gpo** [comment]
Will refresh and get those too tonight.

**Comment by jzheng-gpo** [comment]
Both are showing up now.

**Comment by anerbovig** [comment]
I see them! Thank you.
