### ISSUE TITLE
S309 Typo - wrong congress

### ISSUE THREAD

**Issue by acmcneal** [usgpo/bill-status#121]
Hello!

There is a typo on the bill text for S. 309 (https://www.congress.gov/bill/116th-congress/senate-bill/309/text?q=%7B%22search%22%3A%5B%22s309%22%5D%7D&r=1&s=1)

The file currently says that this bill was introduced in the 1st Session of the 115th Congress; it should instead say 1st Session of the 116th Congress. Hoping this can be corrected - thanks!

**Comment by llaplant** [comment]
S. 309 IS was printed with the incorrect Congress designation. The Senate has decided not to star print S. 309 IS.
