### ISSUE TITLE
sitemapindex is empty. 

### ISSUE THREAD

**Issue by mooncalfskb** [usgpo/bill-status#122]
Hi. We are dependent on this page:
https://www.govinfo.gov/sitemap/bulkdata/sitemapindex.xml

That appears to be now empty. Have you changed your code?
It used to list subpages, like this:

https://www.govinfo.gov/sitemap/bulkdata/BILLSTATUS/115s/sitemap.xml

thanks
Sherrod

**Comment by jonquandt** [comment]
@mooncalfskb -- I'm going to close this one, since we already have this as part of the bulkdata issue list here. Going through and resolving a few more so that the sitemapindex looks correct.

https://github.com/usgpo/bulk-data/issues/37
