### ISSUE TITLE
False latest action for HR 1112

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#124]
Given that this bill has passed the House, I don't believe this latest action for HR 1112 can be correct?

     <item>
        <actionDate>2019-03-22</actionDate>
        <committee>
          <name>Crime, Terrorism, and Homeland Security Subcommittee</name>
          <systemCode>hsju08</systemCode>
        </committee>
        <links />
        <sourceSystem>
          <name>House committee actions</name>
          <code>1</code>
        </sourceSystem>
        <text>Referred to the Subcommittee on Crime, Terrorism, and Homeland Security.</text>
        <type>Committee</type>
      </item>

**Comment by 104PL104** [comment]
Thank you for reporting this. We are investigating.

**Comment by llaplant** [comment]
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr1112.xml
