### ISSUE TITLE
Update Subcommittee Name for the House Foreign Affairs Europe Subcommittee

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#126]
Good morning, the House Foreign Affairs Subcommittee on Europe, Eurasia, and Emerging Threats has updated its name in the 116th to be the "Subcommittee on Europe, Eurasia, Energy, and the Environment."

For bills referred to this subcommittee, the title is correct in the action text, but not under the committee element: https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr2047.xml

<committee>
<systemCode>hsfa14</systemCode>
<name>Europe, Eurasia, and Emerging Threats Subcommittee</name>
</committee>
<links/>
<sourceSystem>
<code>1</code>
<name>House committee actions</name>
</sourceSystem>
<text>
Referred to the Subcommittee on Europe, Eurasia, Energy and the Environment.
</text>

Could this be updated? Thank you.

**Comment by 104PL104** [comment]
Thank you for reporting this. We are investigating.

**Comment by 104PL104** [comment]
This has been corrected at the source. Expect the correction to flow through to Bulk Data soon.

**Comment by anerbovig** [comment]
Thank you.

**Comment by llaplant** [comment]
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr2047.xml
