### ISSUE TITLE
BILLSTATUS-114hconres125.xml --  empty action item

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#13]
This resolution has an empty action and the display on congress.gov  does not seem consistent -- the introduced action in the overview is not listed in all actions:

      <item>
        <actionDate>2016-03-23</actionDate>
        <committee />
        <links />
        <text />
      </item>
      <item>

Is this bad data?

**Comment by 104PL104** [comment]
That empty element is a remnant from legacy systems. We have scheduled work to suppress the empty action items.

**Comment by 104PL104** [comment]
This should be resolved now
