### ISSUE TITLE
House Bills introduced 7/26 are missing sponsors and title

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#134]
House Bills HR 4080 through HR 4090 are missing sponsors and titles.

For example:

https://www.congress.gov/bill/116th-congress/house-bill/4090

![image](https://user-images.githubusercontent.com/33063619/62045920-ae7b2580-b1d4-11e9-8ec4-13ce900a7546.png)

**Comment by adk2009** [comment]
Thank you for reporting.  This issue is now resolved. Please see https://www.congress.gov/search?q=%7B%22congress%22%3A%22116%22%2C%22source%22%3A%22legislation%22%7D&searchResultViewType=expanded

**Comment by kboyd35** [comment]
This is happening again with the 7/30 house bills.

https://www.congress.gov/bill/116th-congress/house-bill/4139

**Comment by adk2009** [comment]
Thank you, a fix is in progress. We will follow up soon.

**Comment by adk2009** [comment]
This is an update to let you know that this issue has been resolved.

**Comment by llaplant** [comment]
Updated congress.gov source data and govinfo.gov bulk data.
