### ISSUE TITLE
bill summary updateDate vs lastSummaryUpdateDate

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#14]
billSummaries has:

```
    <updateDate>2013-03-04T05:00:00Z</updateDate>
    <lastSummaryUpdateDate>2013-04-03T20:33:09Z</lastSummaryUpdateDate>
```

([BILLSTATUS-113s438.xml](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/113/s/BILLSTATUS-113s438.xml))

What's the difference in meaning between these nodes? (In this example the dates are different and the bill has just this one summary.)

Relatedly, are the summaries billSummaries in any particular order (oldest to newest, newest to oldest)?

**Comment by 104PL104** [comment]
No, billSummaries are not listed in a particular order. See Table 5 "Mapping of LOC Summaries Version Codes and Action Description Text" in the User Guide to gain familiarity.

Investigating the date question.

**Comment by llaplant** [comment]
113th Congress BILLSTATUS was reprocessed recently and has a new updateDate. 
  
        <updateDate>2016-06-12T03:25:45Z</updateDate> 

[BILLSTATUS-113s438.xml](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/113/s/BILLSTATUS-113s438.xml) 

lastSummaryUpdateDate applies to billSummaries

**Comment by llaplant** [comment]
Closing out older issues. Documentation updated https://github.com/usgpo/bill-status/blob/master/BILLSTATUS-XML_User_User-Guide.md#summaries.

**Comment by JoshData** [comment]
Thanks!
