### ISSUE TITLE
Final Signed / Became Public Law out of order

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#140]
There are six bills that have the final two actions _Signed by President_ and _Became Public Law No: X-Y._ out of order, as if the bill became law before it was signed. These actions come without times, and they occurred on the same date, and maybe they come from different data sources, so I could understand if they're not supposed to be considered ordered, but this is the first time this problem has occurred in the whole Congress.gov dataset, so I think it's an error.

![image](https://user-images.githubusercontent.com/445875/64488680-94dbed80-d218-11e9-83fd-8b93334c3d6d.png)

[H.R. 540](https://www.congress.gov/bill/116th-congress/house-bill/540/actions)
[H.R. 828](https://www.congress.gov/bill/116th-congress/house-bill/828/actions)
[H.R. 829](https://www.congress.gov/bill/116th-congress/house-bill/829/actions)
[H.R. 1198](https://www.congress.gov/bill/116th-congress/house-bill/1198/actions)
[H.R. 1449](https://www.congress.gov/bill/116th-congress/house-bill/1449/actions)
[H.R. 3305](https://www.congress.gov/bill/116th-congress/house-bill/3305/actions)

This is confusing the https://github.com/unitedstates/congress/ scraper.

**Comment by llaplant** [comment]
Reprocessing from updated Congress.gov source data.

**Comment by llaplant** [comment]
Updated on congress.gov and govinfo.gov 

https://www.govinfo.gov/sitemap/bulkdata/BILLSTATUS/116hr/sitemap.xml

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr540.xml
<lastmod>2019-09-09T15:03:00.298Z</lastmod>

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr828.xml
<lastmod>2019-09-09T15:04:00.570Z</lastmod>

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr829.xml
<lastmod>2019-09-09T15:03:00.382Z</lastmod>

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr1198.xml
<lastmod>2019-09-09T15:03:00.466Z</lastmod>

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr1449.xml
<lastmod>2019-09-09T15:02:00.796Z</lastmod>

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr3305.xml
<lastmod>2019-09-09T15:02:00.887Z</lastmod>

**Comment by JoshData** [comment]
Thanks!

**Comment by JoshData** [comment]
There's a similar issue with HR 4285. It looks fine on Congress.gov, but in the XML (https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr4285.xml) one of the `Became Public Law No` actions (there are multiple, as is normal, from different source systems) precedes the Presented/Signed actions.

**Comment by jzheng-gpo** [comment]
Reprocessed. Please review.

**Comment by JoshData** [comment]
Thanks!
