### ISSUE TITLE
An introduced bill is up on congress.gov but is not yet available in the bulk status feed.

### ISSUE THREAD

**Issue by boisvert1975** [usgpo/bill-status#142]
file is: https://congress.gov/bill/116th-congress/house-resolution/4993

**Comment by boisvert1975** [comment]
The above should be https://congress.gov/bill/116th-congress/house-bill/4993

**Comment by gpo-billstatus** [comment]
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr4993.xml

**Comment by jzheng-gpo** [comment]
It is in now. Please review.
