### ISSUE TITLE
Non-Standard Committee Names in Bill Digest Files

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#143]
Good morning, 

A handful of updated bill digests changed the <name> element under <committees> in the bill digest files, even though the <systemCode> is consistent. 

For example, in September the bill digest file for S. 609 had:
"<name>Health, Education, Labor, and Pensions Committee</name>"

The latest update from 11/16 changed this to:
"<name>HELP Committee</name>"

For H.R. 3020, the committee named in the 11/08 digest was:
"<name>House Transportation and Infrastructure</name>"

The 11/16 update changed the name to:
"<name>House Transportation</name>"

The name variants are causing some hiccups on our end even though the system code is correct. Would it be possible to return the committee names to their standard format for all bills that were referred to the Transportation and Infrastructure and Health, Education, Labor, and Pensions committees? Thank you!

Edit: It looks like it's causing the same problems on Congress.gov--when I filter for legislation under the Senate Health, Education, Labor, and Pensions committee, I get zero results for the 115th and 116th Congresses: https://www.congress.gov/search?searchResultViewType=expanded&q=%7B%22source%22%3A%22legislation%22%2C%22senate-committee%22%3A%22Health%2C+Education%2C+Labor%2C+and+Pensions%22%7D

**Comment by 104PL104** [comment]
Thank you for reporting this. We will get it corrected ASAP.

**Comment by anerbovig** [comment]
Hello, following up on this one, is this how we should expect to see committee names come through going forward, or will the bill digests be updated with the full name for Senate Health, Education, Labor, and Pensions under the <committees> element? The following bill digests came through a 2/10 update with "Senate HELP" listed which is throwing off some name matching on our end. Thanks!

``<billStatus>
<bill>
<billNumber>3114</billNumber>
<createDate>2019-12-20T05:57:22Z</createDate>
<updateDate>2020-02-10T17:07:10Z</updateDate>
<originChamber>Senate</originChamber>
<billType>S</billType>
<introducedDate>2019-12-19</introducedDate>
<congress>116</congress>
<recordedVotes/>
<committees>
<billCommittees>
<item>
<systemCode>sshr00</systemCode>
<name>HELP Committee</name>
<chamber>Senate</chamber>
<type>Standing</type>
<subcommittees/>
<activities>
<item>
<name>Referred to</name>
<date>2019-12-19T18:15:46Z</date>
</item>
</activities>
</item>
</billCommittees>
</committees>

**Comment by llaplant** [comment]
Source data is being corrected and BILLSTATUS files on govinfo will be updated shortly.

**Comment by jzheng-gpo** [comment]
All 97 files are refreshed now. Please review.

**Comment by anerbovig** [comment]
Thank you! I see that the committee element now has "Health, Education, Labor, and Pensions Committee"
