### ISSUE TITLE
Bill status for HR3889 is not updated

### ISSUE THREAD

**Issue by aih** [usgpo/bill-status#144]
An enrolled bill is available for HR3889 (https://www.govinfo.gov/content/pkg/BILLS-116hr3889enr/xml/BILLS-116hr3889enr.xml), but the bill status currently only shows the 'ih' version:

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr3389.xml

What is the timing of the update for the 'billstatus'? It would be ideal (for work with LRC) if 'enr' bill status were updated ASAP.

**Comment by jzheng-gpo** [comment]
Just kicked off a refresh manually.

**Comment by aih** [comment]
Thank you!!!

In general, what is the expected timing for an 'enr' bill to show up in the status?

**Comment by aih** [comment]
The bill, `hr3389`, does not appear in the list of bill statuses recently updated:
`https://api.govinfo.gov/collections/BILLS/2019-11-01T20:18:10Z/2019-11-20T19:20:10Z?offset=0&pageSize=10000` (requires `api_key`), and the `textVersions` element still does not have an entry for the `enr` bill:
`https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr3389.xml`
```
<textVersions>
<item>
<type>Introduced in House</type>
<date>2019-06-20T04:00:00Z</date>
<formats>
<item>
<url>
https://www.govinfo.gov/content/pkg/BILLS-116hr3389ih/xml/BILLS-116hr3389ih.xml
</url>
</item>
</formats>
</item>
</textVersions>
```

**Comment by llaplant** [comment]
@aih could you clarify H.R. 3389 or H.R. 3889? Both are referenced above. Thanks!

**Comment by aih** [comment]
My mistake! I'm referencing HR3889. I now see that it has an updateDate of `2019-11-20T21:30:33Z`, and has the `enr` bill version in `textVersions`, in the link @llaplant showed above.

(I've updated the title of this issue, but left my incorrect reference to hr3389 in the comment above)

**Comment by aih** [comment]
I'm closing this issue, as the update is available. Thanks, @llaplant  and @jzheng-gpo !
