### ISSUE TITLE
Introduced senate bills from 11/21 are not yet available in the Bill Status Bulk Data

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#145]
The Senate bills introduced 11/21 are available on congress.gov but are not yet available int he bulk status feed.

For example:
https://www.congress.gov/bill/116th-congress/senate-bill/2958

**Comment by jzheng-gpo** [comment]
Refreshed now. Please review.

**Comment by kboyd35** [comment]
This is fixed now.
