### ISSUE TITLE
Bill status for bills last week (11/25/19) do not seem to be updated

### ISSUE THREAD

**Issue by aih** [usgpo/bill-status#146]
Twelve new bills were enrolled last week: H.R. 887, H.R. 1252, H.R. 1253, H.R. 1526, H.R. 1844, H.R. 1972, H.R. 2151, H.R. 2325, H.R. 2334, H.R. 2451, H.R. 3144, H.R. 3314.

The content for these is in govinfo (e.g. https://www.govinfo.gov/content/pkg/BILLS-116hr887enr/pdf/BILLS-116hr887enr.pdf, https://www.govinfo.gov/content/pkg/BILLS-116hr887enr/xml/BILLS-116hr887enr.xml).

However, the bill status, in particular `textVersions` do not seem to have been updated yet. E.g. 
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr887.xml

![image](https://user-images.githubusercontent.com/217356/69972498-909d3480-14d6-11ea-8da9-349a73a56cd0.png)

**Comment by llaplant** [comment]
@aih They are available. 
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr887.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr1252.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr1253.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr1526.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr1844.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr1972.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr2151.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr2351.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr2325.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr2334.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr2451.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr3144.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr3313.xml

**Comment by aih** [comment]
Perfect. Thanks!

**Comment by aih** [comment]
Confirming:
![image](https://user-images.githubusercontent.com/217356/69980225-a6b1f180-14e4-11ea-80a5-fd22f67f3f5e.png)
