### ISSUE TITLE
Introduced senate bills from 1/21 are not yet available in the Bill Status Bulk Data

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#148]
Introduced senate bills and resolutions from 1/21 are available on congress.gov but are not yet available in the Bill Status Bulk data feed.

For example:

https://www.congress.gov/bill/116th-congress/senate-bill/3226

https://www.congress.gov/bill/116th-congress/senate-resolution/483

**Comment by gpo-billstatus** [comment]
Available now.  Thanks.
