### ISSUE TITLE
bill is missing sponsor (on Congress.gov too)

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#15]
S. 414  in the 113th is missing sponsor info:
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/113/s/BILLSTATUS-113s414.xml

Same at:
https://www.congress.gov/bill/113th-congress/senate-bill/414

THOMAS had it whenever I last scraped:
https://www.govtrack.us/congress/bills/113/s414

**Comment by 104PL104** [comment]
resolved

**Comment by JoshData** [comment]
Thanks!
