### ISSUE TITLE
Missing cosponsor

### ISSUE THREAD

**Issue by sun-yujia** [usgpo/bill-status#150]
Hello, 

On S.2948, Sen. Jacky Rosen was [added](https://www.congress.gov/congressional-record/2020/01/14/senate-section/article/S193-3) as a co-sponsor a few weeks ago. This addition shows up on the [congress.gov website](https://www.congress.gov/bill/116th-congress/senate-bill/2948/cosponsors?searchResultViewType=expanded&KWICView=false), but not the [govinfo source link](https://www.govinfo.gov/bulkdata/BILLSTATUS/116/s/BILLSTATUS-116s2948.xml). 

Could you look into this? Thank you!

**Comment by jzheng-gpo** [comment]
Refreshed now. Please review.

**Comment by sun-yujia** [comment]
Hello, I noticed that many of the bills from that [specific day (1/14/2020)](https://www.congress.gov/congressional-record/2020/01/14/senate-section/article/S193-3) also had sponsors missing. For example, S701 doesn't have Sen. Coons listed as a co-sponsor. This issue appears to be present for all the bills except the last five on the record. 

Could you look into the bills from that particular day? Thank you!

**Comment by jzheng-gpo** [comment]
I have started to process the packages between 1/13 to 1/15. I will verify some package after finish. Thanks.

**Comment by jzheng-gpo** [comment]
Refreshed now. I see S701 updated now.
