### ISSUE TITLE
Update Bill Status to Include latest Bill Versions

### ISSUE THREAD

**Issue by kbritton3** [usgpo/bill-status#151]
The bill status for these bills don't include references to the following bill versions that have been added:

H.R. 1132 (EH)
H.R. 1620 (EH)
H.R. 2247 (EH)
H.R. 2382 (EH)
H.R. 3317 (EH)
H.R. 3830 (EH)
H.R. 3941 (EH)
H.R. 3976 (EH)
H.R. 4031 (EH)
H.R. 4044 (EH)
H.R. 4275 (EH)
H.R. 4279 (EH)
H.R. 4305 (EH)
H.R. 4794 (EH)
H.R. 4981 (EH)
H.R. 5037 (EH)
H.R. 5214 (EH)

**Comment by gpo-billstatus** [comment]
Update just finished.  They are there now. Thanks.
