### ISSUE TITLE
Incorrect Senate Homeland Subcommittee Name

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#152]
In the bulk data source on govinfo.gov, some Senate bills have the incorrect subcommittee name for the Homeland Security and Governmental Affairs Subcommittee on Regulatory Affairs and Federal Management:

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/s/BILLSTATUS-116s1120.xml

```
<subcommittees>
<item>
<systemCode>ssga19</systemCode>
<name>and Federal Management Subcommittee</name>
<activities>
<item>
<name>Hearings by</name>
<date>2019-05-22T18:31:34Z</date>
</item>
</activities>
</item>
</subcommittees>
```

The subcommittee name has been truncated to remove "Regulatory Affairs", and it's incorrect in the subcommittee listing as well as the bill actions. The text of the action has the correct full name of the subcommittee: 

```
<item>
<actionDate>2019-05-22</actionDate>
<committees>
<item>
<systemCode>ssga19</systemCode>
<name>and Federal Management Subcommittee</name>
</item>
</committees>
<links/>
<sourceSystem>
<code>0</code>
<name>Senate</name>
</sourceSystem>
<text>
Committee on Homeland Security and Governmental Affairs Subcommittee on Regulatory Affairs and Federal Management. Hearings held.
</text>
<type>Committee</type>
</item>
```

This is affecting the following bills in the 116th Congress:
S. 1419
S. 83
S. 1120
S. 1339
S. 78
S. 1409
S. 1420

**Comment by llaplant** [comment]
Contacting legislative data partners to update in source data and will reprocess impacted bill status files when updated source data is available. Thanks for letting us know about this!

**Comment by jzheng-gpo** [comment]
Above listed bills have been updated. Please review.

**Comment by anerbovig** [comment]
Fixed on our end, thank you!
