### ISSUE TITLE
Missing XML/HTML Bill Versions on Congress.gov

### ISSUE THREAD

**Issue by kbritton3** [usgpo/bill-status#153]
Congress.gov is missing the XML/HTML versions of the following bills: 
HR6216_IH
HR6239_IH
HR6240_IH
HR6243_IH
HR6246_IH
HR6250_IH
HR6249_IH
HR6251_IH
HR6252_IH
HR6253_IH
HR6254_IH
HR6257_IH
HR6259_IH
HR6260_IH
HR6263_IH
HR6261_IH
HR6262_IH
HR6264_IH
HR6273_IH
HR6277_IH
HR6274_IH
HR6285_IH
HR6271_IH
HR6291_IH
HR6294_IH
HR6299_IH
HR6304_IH
HR6306_IH
HR6307_IH
HR6310_IH
HR6309_IH
HR6311_IH
HR6292_IH
HRES914_IH
HR6322_IH
HR6425_IH
HR6282_IH
HR6283_IH
HR6286_IH
HR6284_IH
HR6287_IH
HR6288_IH
HR6290_IH
HR6289_IH
HR6301_IH
HR6303_IH
HR6322_EH
HR6217_IH
HR6227_IH
HR6229_IH
HR6230_IH
HR6231_IH
HR6233_IH
HR6232_IH
HR6235_IH
HR6236_IH
HR6234_IH
HR6237_IH
HR6238_IH
HR6241_IH
HR6242_IH
HR6244_IH
HR6245_IH
HR6265_IH
HR6268_IH
HR6269_IH
HR6270_IH
HR6224_IH
HR6248_IH
HR6266_IH
HR6272_IH
HR6275_IH
HR6276_IH
HR6278_IH
HR6279_IH
HR6280_IH
HR6281_IH
HR6293_IH
HR6295_IH
HR6296_IH
HR6297_IH
HR6298_IH
HR6300_IH
HR4771_ENR

Can these be added?

**Comment by 104PL104** [comment]
Thank you. Yes. We are working on this.

**Comment by 104PL104** [comment]
All are fixed, except HR4771_ENR. We are working on that one now.

**Comment by 104PL104** [comment]
Thank you for reporting this. The issue has been resolved.
