### ISSUE TITLE
Introduced bills from 7/13 are not yet available ont he bulk data feed.

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#155]
Introduced bills from yesterday are up on congress.gov but are not yet available in the bulk status feed.

For example:
https://www.congress.gov/bill/116th-congress/house-bill/7610

**Comment by jzheng-gpo** [comment]
Running a manual refresh now.

**Comment by wcarter** [comment]
I am still not seeing any updates.

**Comment by jzheng-gpo** [comment]
Our up stream site has functioning issue and data could not be pulled down at this point. Will update once this issue is resolved.

**Comment by wcarter** [comment]
thanks.

**Comment by jzheng-gpo** [comment]
These new bills are available now. Please review.

**Comment by llaplant** [comment]
Closing resolved issue.
