### ISSUE TITLE
Introduced bills from 12/3 are not yet available on the bulk data feed

### ISSUE THREAD

**Issue by acmcneal** [usgpo/bill-status#156]
Introduced bills from yesterday are up on congress.gov but are not yet available in the bulk status feed.

**Comment by jzheng-gpo** [comment]
I will kick off the billstatus 116 again and will let you know when completes. The last run was at middle night and did pickup new bills.

**Comment by jzheng-gpo** [comment]
The job is still running. Below is new bills, please review:
116hr8869
116hres1249
116s4965
116sconres50
116sres793

**Comment by acmcneal** [comment]
I see the new bills in the bulk data feed now, thank you!
