### ISSUE TITLE
Introduced bills from 12/8 are not yet available on the bulk data feed

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#159]
For example:  https://www.congress.gov/bill/116th-congress/house-bill/8905

**Comment by llaplant** [comment]
A batch is currently processing and this particular file was made available a few minutes ago. https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr8905.xml

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr

**Comment by wcarter** [comment]
Thank you!
