### ISSUE TITLE
amendment info appears to be in the wrong place

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#16]
In [BILLSTATUS-114s754.xml](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s754.xml), the info for S.Amdt. 2547 appears to have been generated incorrectly. Amendment top-level elements like `sponsors`, `amendedBill` etc. are inside the `actionByCounts` node:

![image](https://cloud.githubusercontent.com/assets/445875/16432076/8c9b40c6-3d51-11e6-96a9-5fb843bf1206.png)

**Comment by JoshData** [comment]
Also in BILLSTATUS-114s2943.xml S.Amdts. 4136, 4137, 4139, 4140, 4141 and others.

**Comment by llaplant** [comment]
Code deployed to Production and reprocessed [BILLSTATUS-114s754.xml](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s754.xml).

**Comment by JoshData** [comment]
Thanks!
