### ISSUE TITLE
Bill Status does not contain enrolled bills for bills recently enrolled in the House

### ISSUE THREAD

**Issue by aih** [usgpo/bill-status#160]
There are ~20 bills that were enrolled Tuesday, December 8 in the House. These do not seem to be included in their corresponding Bill Status XML. For example:

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr2454.xml

Text versions include: rfs, eh, ih, but not enr

The enr version *is* listed in the BILLS API:

https://api.govinfo.gov/collections/BILLS/2020-12-07T00:00:00Z?pageSize=100&offset=0

And is available from the packages API:
https://api.govinfo.gov/packages/BILLS-116hr2454enr/xml

**Comment by jonquandt** [comment]
@aih 

looks like that BILLSTATUS package just updated: 
https://api.govinfo.gov/packages/BILLSTATUS-116hr2454/summary?api_key=DEMO_KEY 

```json
{
  "collectionCode": "BILLSTATUS",
  "collectionName": "Congressional Bill Status",
  "category": "Bills and Statutes",
  "dateIssued": "2020-12-10",
  "packageId": "BILLSTATUS-116hr2454",
  "download": {
    "xmlLink": "https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr2454.xml"
  },
  "branch": "legislative",
  "governmentAuthor1": "Library of Congress",
  "governmentAuthor2": "Congressional Research Service",
  "billType": "hr",
  "congress": "116",
  "billNumber": "2454",
  "lastModified": "2020-12-10T15:14:44Z"
}

It now includes the enrolled version BILLS xml link in the BILLSTATUS xml:

```xml
<textVersions>
<item>
<type>Enrolled Bill</type>
<date/>
<formats>
<item>
<url>https://www.govinfo.gov/content/pkg/BILLS-116hr2454enr/xml/BILLS-116hr2454enr.xml</url>
</item>
</formats>
</item>
```

I believe the delay was because of large 116th congress update that delayed processing. In any case, 21 additional BILLSTATUS files with associate enrolled bills should now be showing up correctly. 

Let us know if you see any issues.

**Comment by aih** [comment]
Thank you for your fast resolution of this issue (and explanation)!! This was a production issue for us. I'm closing, pending any issue I might see downstream.
