### ISSUE TITLE
Introduced bills from 1/19/2021 are available on congress.gov but not yet in bulk data feed

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#166]
For example:  https://www.congress.gov/bill/117th-congress/house-bill/372

Is an update coming soon?  I appreciate this is an unusual day!

**Comment by jzheng-gpo** [comment]
Working on them now.

**Comment by jzheng-gpo** [comment]
117th congress is up to date now:
hr 372
sres 5
