### ISSUE TITLE
Incorrect Official Title on S473

### ISSUE THREAD

**Issue by acmcneal** [usgpo/bill-status#168]
The official title is written incorrectly.  

It reads “subset” instead of “sunset”. The official text listed in the pdf is: “To amend the CARES Act to extend the sunset for the definition of a small business debtor, and for other purposes.”

**Comment by llaplant** [comment]
Thank you for bringing this to our attention. The source data will be corrected, and I will let you know when the BILLSTATUS XML file on govinfo has been updated.

**Comment by llaplant** [comment]
Updated and available at
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/s/BILLSTATUS-117s473.xml
