### ISSUE TITLE
actionTime in the old format

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#17]
[BILLSTATUS-113hconres14.xml](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/113/hconres/BILLSTATUS-113hconres14.xml) has `actionTime`s in the old XX:YY AM/PM format instead of the newer ISO-like format:

    <item>
        <actionCode>H38310</actionCode>
        <actionDate>2013-03-06</actionDate>
        <actionTime>12:00PM</actionTime>

**Comment by JoshData** [comment]
...and also in about 500 other files in the 113th Congress.

**Comment by llaplant** [comment]
Reprocessing 113th Congress to update date format.

**Comment by llaplant** [comment]
Reprocessing of 113 is complete. See [BILLSTATUS-113hconres14.xml](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/113/hconres/BILLSTATUS-113hconres14.xml)

**Comment by JoshData** [comment]
Thanks.
