### ISSUE TITLE
Introduced Bills from 3/29/21 are not up on the bulk data feed

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#170]
Introduced bills from yesterday are not up on the bulk data feed, but are available on congress.gov

For example: https://www.congress.gov/bill/117th-congress/house-bill/2292

**Comment by jzheng-gpo** [comment]
It is under refreshing and might take an hour.

**Comment by gpo-billstatus** [comment]
Available now.  https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr2292.xml

From: kboyd35 ***@***.***>
Sent: Tuesday, March 30, 2021 11:49 AM
To: usgpo/bill-status ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [usgpo/bill-status] Introduced Bills from 3/29/21 are not up on the bulk data feed (#170)


Introduced bills from yesterday are not up on the bulk data feed, but are available on congress.gov

For example: https://www.congress.gov/bill/117th-congress/house-bill/2292<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.congress.gov%2Fbill%2F117th-congress%2Fhouse-bill%2F2292&data=04%7C01%7Cazhang%40gpo.gov%7C03eb3b6030c04952a88f08d8f3936416%7C97ae4de0d4584af3a7df1c19bdbe49d0%7C0%7C0%7C637527161664129424%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SIl6gTD5FGuTGpMrJ%2FWxNh2Wgg%2BBSaCNn%2FzeZs%2Ffl48%3D&reserved=0>

-

**Comment by kboyd35** [comment]
Thank you.
