### ISSUE TITLE
Introduced Bills from 7/26/21 are not up on the bulk data feed

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#174]
Introduced Bills from 7/26/21 are available on congress.gov but are not yet available on the bulk status feed.

For example: 
https://www.congress.gov/bill/117th-congress/house-bill/4697
https://www.congress.gov/bill/117th-congress/senate-bill/2474
https://www.congress.gov/bill/117th-congress/house-resolution/562
https://www.congress.gov/bill/117th-congress/senate-bill/2474

**Comment by jzheng-gpo** [comment]
These are up to date now. Please review.

**Comment by kboyd35** [comment]
Confirmed that they are updated now.
