### ISSUE TITLE
Missing Links to Amendment Roll Calls

### ISSUE THREAD

**Issue by jose-pvargas** [usgpo/bill-status#177]
Per the [documentation](https://github.com/usgpo/bill-status/blob/master/BILLSTATUS-XML_User_User-Guide.md#amendments) on amendments, I am expecting to find links to the roll call XML. However, amendments with roll calls, such as the [115th Congress's S. Amdt 667](https://www.congress.gov/amendment/115th-congress/senate-amendment/667) and the [117th Congress's S.Amdt 889](https://www.congress.gov/amendment/117th-congress/senate-amendment/889) do not have corresponding links to the roll call XML.

I've attached the BILLSTATUS XML for the resolutions that each amendment corresponds to, HR 1628 and SCONRES 5, respectively. [bills-with-amendments-missing-rollcall-links.zip](https://github.com/usgpo/bill-status/files/7281085/bills-with-amendments-missing-rollcall-links.zip)

**Comment by llaplant** [comment]
Hi, if possible, in lieu of a ZIP file, could you add a list of access ids to this issue? Thanks!
Example:
BILLSTATUS-117sconres5

**Comment by jose-pvargas** [comment]
Sure!

`BILLSTATUS-117sconres5` and `BILLSTATUS-115hr1628` are the two resolutions that I checked where I expected links to amendment roll calls.

**Comment by llaplant** [comment]
Thank you for bringing this to our attention!  
It will likely require a code change that will be scheduled into an upcoming release.

**Comment by llaplant** [comment]
@jose-pvargas, I added sample data from our development environment to https://github.com/usgpo/bill-status/tree/master/samples/amendment-votes. Could you check it out and let me know what you think?

**Comment by llaplant** [comment]
Tagging a few more people who have recently submitted issues to this repo. If you would also like to take a look, sample data from our development environment is in https://github.com/usgpo/bill-status/tree/master/samples/amendment-votes 


@boisvert1975, @kboyd35, @joshdata, @wcarter, @dwillis, @acmcneal, @kbritton3, @sun-yujia, @aih, @anerbovig

**Comment by michaelstephenson0613** [comment]
> Hi, if possible, in lieu of a ZIP file, could you add a list of access ids to this issue? Thanks! Example: BILLSTATUS-117sconres5

**Comment by jose-pvargas** [comment]
Thanks for providing the updated samples @llaplant. I compared the samples that you shared with what we used to receive and previously, House votes would only include the XML URL in the `<link>` element. So for [HR 5278](https://github.com/usgpo/bill-status/blob/master/samples/amendment-votes/BILLSTATUS-114hr5278.xml), instead of 
```xml
<links>
  <link>
    <name>Roll no. 287</name>
    <url>https://clerk.house.gov/Votes/2016287</url>
    <url>https://clerk.house.gov/evs/2016/roll287.xml</url>
  </link>
</links>
```

we would previously receive
```xml
<links>
  <link>
    <name>Roll no. 287</name>
    <url>https://clerk.house.gov/evs/2016/roll287.xml</url>
  </link>
</links>
```

Is this something that can be handled on your end to keep backwards compatibility? Otherwise, we'll need to update our client to ignore non-XML URLs for House votes.

The XML for the Senate vote links look the same.

**Comment by llaplant** [comment]
@jose-pvargas new sample files are available https://github.com/usgpo/bill-status/tree/master/samples/amendment-votes

**Comment by jose-pvargas** [comment]
@llaplant The data looks good to me. Thanks for the update!

**Comment by jose-pvargas** [comment]
Hi @llaplant, do you have an update on when this will be released?

**Comment by llaplant** [comment]
@jose-pvargas, we are working with our data partners, and if all goes well we are targeting the end of next week. Due to a recent update, this change requires coordination on deployments for systems at two different organizations.

**Comment by llaplant** [comment]
@jose-pvargas, please let us know if this meets expectations. 

https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr5278.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/sconres/BILLSTATUS-117sconres5.xml

**Comment by jose-pvargas** [comment]
Thanks @llaplant. SCONRES 5 looks good. However, for https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr5278.xml, the link to rollcall https://clerk.house.gov/evs/2016/roll287.xml only appears under the `latestAction` section, and not under the individual action elements as mentioned in the [amendment documentation](https://github.com/usgpo/bill-status/blob/master/BILLSTATUS-XML_User_User-Guide.md#amendments).

**Comment by jonquandt** [comment]
@jose-pvargas - thanks for the note. We are looking into that issue with our data partners.

**Comment by jose-pvargas** [comment]
@jonquandt What's the status of this issue?

**Comment by jonquandt** [comment]
@jose-pvargas 
We're still coordinating with our data partners and awaiting a change in order for that information to flow through again. Timing is TBD, but likely not until Spring.

**Comment by 104PL104** [comment]
update - scheduled for fix in PROD on June 13, 2022

**Comment by llaplant** [comment]
Links to roll call votes appear under the latestAction section and also the individual action element. Example  https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr5278.xml.
