### ISSUE TITLE
Introduced bill from 10/18 are not yet available in the Bill Status Bulk Data

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#178]
Senate bills and resolutions introduced 10/18 are not yet available on the bulk data feed but are on congress.gov

For example:
https://www.congress.gov/bill/117th-congress/senate-bill/2992
https://www.congress.gov/bill/117th-congress/senate-resolution/421

**Comment by kboyd35** [comment]
Can you please check on the introduced bills from 10/19?
For example 117S3012, 117SRES423, 117HR5634, and 117HRES726

**Comment by jzheng-gpo** [comment]
These new bills are available now. The refreshing job is still running for updating existing ones:
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/s/BILLSTATUS-117s3012.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/sres/BILLSTATUS-117sres423.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5634.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hres/BILLSTATUS-117hres726.xml

**Comment by llaplant** [comment]
Verified bills are available and closing issue.
