### ISSUE TITLE
S1218 False Action

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#179]
There is a false action for "Presented to the President" the following bill:
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/s/BILLSTATUS-117s1218.xml

<item>
<actionDate>2021-11-09</actionDate>
<links/>
<text>Presented to President.</text>
<type>Floor</type>
<actionCode>E20000</actionCode>
<sourceSystem>
<code>2</code>
<name>House floor actions</name>
</sourceSystem>
<committees/>
</item>

This action appears to have already been corrected on congress.gov:
https://www.congress.gov/bill/117th-congress/senate-bill/1218/all-actions

**Comment by llaplant** [comment]
Reprocessed. Please check.

**Comment by kboyd35** [comment]
This has been resolved.
