### ISSUE TITLE
What is the timing in terms of updating sitemap and bulk data directory/zip?

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#18]
I am seeing bills in:

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr

that are not yet on:

https://www.gpo.gov/smap/bulkdata/BILLSTATUS/114hr/sitemap.xml

**Comment by jonquandt** [comment]
@wcarter, could you give me an example or two?

I noticed that the sitemap link you reference is for Senate bills. Are the missing bills available here:

https://www.gpo.gov/smap/bulkdata/BILLSTATUS/114hr/sitemap.xml

**Comment by wcarter** [comment]
yes I updated my link, sorry.  I am relatively confident I was looking at the right sitemap and saw a discrepancy but it is in sync now.  Perhaps it was a caching issue on my end.

**Comment by jonquandt** [comment]
Ok -- if you see the issue again, please re-open the issue so we can investigate. Thanks!
