### ISSUE TITLE
BILLSTATUS-117hr4350 URL for Senate Vote 472

### ISSUE THREAD

**Issue by llaplant** [usgpo/bill-status#184]
In BILLSTATUS-117hr4350, the link for Senate roll call vote number 472 does not resolve. The provided Senate vote URL is: http://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?vote1171/vote_117_1_00472.htm. The Correct URL appears to be: http://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?&congress=117&session=1&vote=00472 (submitted on behalf of user)

**Comment by nickrecchi** [comment]
I wanted to add that this issue appears in other Bill Status bulk data files. In BILLSTATUS-117sconres14, there are additional Senate roll call vote URLs not resolving:

Provided URL:
http://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?vote1171/vote_117_1_00315.htm
Correct URL:
http://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?&congress=117&session=1&vote=00315

Provided URL:
http://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?vote1171/vote_117_1_00357.htm
Correct URL:
http://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?&congress=117&session=1&vote=00357

Thanks @llaplant for submitting this issue for me.

**Comment by llaplant** [comment]
The issue is resolved for the 117th Congress, and we are reprocessing data. 

See https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr4350.xml for an example of a file that has been reprocessed. 

Senate vote URLs resolve to HTML pages like https://www.senate.gov/legislative/LIS/roll_call_votes/vote1171/vote_117_1_00472.htm, but in an upcoming near-term release we are planning to have the Senate URLs point to the XML like this https://www.senate.gov/legislative/LIS/roll_call_votes/vote1171/vote_117_1_00472.xml.

**Comment by nickrecchi** [comment]
Thanks @llaplant for getting this resolved.

I'm also happy to hear the Senate vote URLs will be pointing to the XML in an upcoming release, which will match the behavior of the House vote URLs.

**Comment by llaplant** [comment]
@nickrecchi, take a look at link to Senate vote in XML, and let me know if this meets expectations. 

https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr4350.xml

**Comment by nickrecchi** [comment]
Yes @llaplant, that Senate vote link pointing to the XML is exactly what I was looking for. Thank you.
