### ISSUE TITLE
BILLSTATUS-117hr5314 URLs for House Votes 439 and 440

### ISSUE THREAD

**Issue by nickrecchi** [usgpo/bill-status#187]
BILLSTATUS-117hr5314 contains links that do not resolve for House roll call vote numbers 439 and 440.

The provided House vote URLs are:
https://clerk.house.gov/evs/2021/439.xml
https://clerk.house.gov/evs/2021/440.xml

The correct URLs are:
https://clerk.house.gov/evs/2021/roll439.xml
https://clerk.house.gov/evs/2021/roll440.xml

**Comment by llaplant** [comment]
Thank you for letting us know. We are investigating with our data partners.

**Comment by llaplant** [comment]
This is resolved. https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5314.xml
