### ISSUE TITLE
missing actionTime (THOMAS has it)

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#19]
In [BILLSTATUS-114hconres111.xml](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hconres/BILLSTATUS-114hconres111.xml), and on the [corresponding page on Congress.gov](https://www.congress.gov/bill/114th-congress/house-concurrent-resolution/111/actions), an action item is missing an `actionTime` that THOMAS has.

The bulk data (no `actionTime`):

	<item>
		<type>Discharge</type>
		<text>Committee on House Administration discharged.</text>
		<sourceSystem>
			<code>2</code>
			<name>House floor actions</name>
		</sourceSystem>
		<committee>
			<systemCode>hsha00</systemCode>
			<name>House Administration Committee</name>
		</committee>
		<actionDate>2016-02-10</actionDate>
		<actionCode>H12300</actionCode>
	</item>
	<item>
		<type>Committee</type>
		<text>Committee on House Administration discharged.</text>
		<sourceSystem>
			<code>9</code>
			<name>Library of Congress</name>
		</sourceSystem>
		<committee>
			<systemCode>hsha00</systemCode>
			<name>House Administration Committee</name>
		</committee>
		<actionDate>2016-02-10</actionDate>
		<actionCode>5500</actionCode>
	</item>

THOMAS (I forget how to permalink):

![image](https://cloud.githubusercontent.com/assets/445875/16454466/d5fc9c00-3dde-11e6-8265-d45b849dba45.png)

This isn't really a problem necessarily, but I wanted to flag it in case there's an underlying bug.

**Comment by 104PL104** [comment]
See "actionTime (e.g., 18:16:46; Note: Only present for House floor actions ONLY process timestamps when sourceSystem code value=2)" in the User Guide.

**Comment by JoshData** [comment]
This is a House floor action.

**Comment by 104PL104** [comment]
Good point. We need to further clarify the User Guide note to exclude type=Discharge, and possibly also type=Reported. Those are two paper-pushing type actions that don't happen on the floor. They push paper toward the floor from a committee. No one is recording time stamps for those.

**Comment by JoshData** [comment]
In [BILLSTATUS-114hr3762.xml](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr3762.xml), the veto override roll call vote is missing the time.
