### ISSUE TITLE
Introduced bills from yesterday are up on congress.gov but are not yet available in bulk status feed

### ISSUE THREAD

**Issue by boisvert1975** [usgpo/bill-status#190]
Introduced bills from yesterday are up on congress.gov but are not yet available in bulk status feed.

Such as:

https://www/congress.gov/bill 117th-congress/house-bill/6557 to 6576
https://www/congress.gov/bill 117th-congress/senate-bill/3553 to 3568
https://www/congress.gov/bill 117th-congress/house-resolution/900 to 904

**Comment by jzheng-gpo** [comment]
Above bills are available in bulk data now. The rest of update is running and might take half to one hour.

**Comment by llaplant** [comment]
Closing because files are now available.
