### ISSUE TITLE
Introduced bills from yesterday are up on congress.gov but are not yet available in bulk status feed.

### ISSUE THREAD

**Issue by boisvert1975** [usgpo/bill-status#191]
Introduced bills from yesterday are up on congress.gov but are not yet available in bulk status feed.

Such as:

https://www/congress.gov/bill 117th-congress/house-bill/6617 to 6636
https://www/congress.gov/bill 117th-congress/house-joint-resolution/70
https://www/congress.gov/bill 117th-congress/house-resolution/912 to 913

**Comment by jzheng-gpo** [comment]
Above bills are available now. The refreshing job has completed.
