### ISSUE TITLE
Appropriations field

### ISSUE THREAD

**Issue by melissa337** [usgpo/bill-status#199]
Is the isappropriation: flag still in use? We were not seeing it on bills from the current session and were instead looking here: https://crsreports.congress.gov/AppropriationsStatusTable/Index/AppropriationsStatusTable?id=2022

According to the site it is still available: https://www.govinfo.gov/help/bills#metadata

**Comment by llaplant** [comment]
Thank you for bringing this to our attention. We are investigating.

**Comment by llaplant** [comment]
@melissa337 this should be resolved for 117th Congress forward and we are reprocessing prior Congresses. Example https://www.govinfo.gov/metadata/pkg/BILLS-117hr4502rds/mods.xml. Please let us know if you see any other issues.
