### ISSUE TITLE
official title for other 

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#20]
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr5148.xml

has the following official title item:

<item>
<chamberName/>
<titleType>Official Titles on Other Bill Versions</titleType>
<chamberCode/>
<parentTitleType>Official Title</parentTitleType>
<title>
To amend the Department of Education Organization Act and the Higher Education Act of 1965 to require publication of information relating to religious exemptions to the requirements of title IX of the Education Amendments of 1972, and for other purposes.
</title>
</item>

This is the only bill status file for the 114th congress with this title type. Is it a data error?

**Comment by 104PL104** [comment]
You have referred to the use of a Title Type 9. It is valid. See Table 6. Title Type Possible Values in the User Guide for the complete list.

You are correct that use of Title Type 9 is rare. The other time it has been used in 113th-present data is for [113th] H.R.370
