### ISSUE TITLE
Introduced bills from yesterday are not yet available in the Bill Status Bulk Data 

### ISSUE THREAD

**Issue by boisvert1975** [usgpo/bill-status#201]
Introduced bills from yesterday are up on congress.gov but are not yet available in the bulk status feed.

For example:
https://www.congress.gov/bill/117th-congress/house-bill/9255 to house bill 9260
https://www.congress.gov/bill/117th-congress/house-resolution/1453

**Comment by gpo-billstatus** [comment]
Updating now. Will be available shortly. Thanks.

From: boisvert1975 ***@***.***>
Sent: Tuesday, November 1, 2022 11:26 AM
To: usgpo/bill-status ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [usgpo/bill-status] Introduced bills from yesterday are not yet available in the Bill Status Bulk Data (Issue #201)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Introduced bills from yesterday are up on congress.gov but are not yet available in the bulk status feed.

For example:
https://www.congress.gov/bill/117th-congress/house-bill/9255<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.congress.gov%2Fbill%2F117th-congress%2Fhouse-bill%2F9255&data=05%7C01%7Cazhang%40gpo.gov%7Ce9d3992ed4c8480eebf408dabc1d6919%7C97ae4de0d4584af3a7df1c19bdbe49d0%7C0%7C0%7C638029131783585573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gkw4j6Q2AnzVZvjR30DPMsTlr74%2FPXlTNWu7UCGm%2BgM%3D&reserved=0> to house bill 9260
https://www.congress.gov/bill/117th-congress/house-resolution/1453<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.congress.gov%2Fbill%2F117th-congress%2Fhouse-resolution%2F1453&data=05%7C01%7Cazhang%40gpo.gov%7Ce9d3992ed4c8480eebf408dabc1d6919%7C97ae4de0d4584af3a7df1c19bdbe49d0%7C0%7C0%7C638029131783585573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DigOZlr%2FpmIKrvFuijNOrMAWXv3Am3p6QOhvImAuIZA%3D&reserved=0>

-

**Comment by jzheng-gpo** [comment]
These bills are available online now.
