### ISSUE TITLE
Missing action name in recorded vote

### ISSUE THREAD

**Issue by nickrecchi** [usgpo/bill-status#202]
The fullActionName is no longer in recordedVote (e.g. "Passage of a Measure"), which I've been encountering since the recent 3.0.0 schema update (usgpo/bill-status#200). I didn't see any mention of fullActionName changing in the description of the 3.0.0 format changes. Some impacted bills are:
117hr1917, 117hr7939, 117hr9640

Edit: This issue originally also contained the missing amendments issue, but I later recognized they should be reported as separate issues. The missing amendment issue that used to be mentioned here is now located here:
usgpo/bill-status#209

**Comment by llaplant** [comment]
Per the Library of Congress, fullActionName was removed from v3 of the Congress.gov API in the [September 2022 Release](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-4-2). It was missed in the description of changes in (#200). Thank you for bringing this to our attention. As noted, the amendment issue is being tracked in #209.

**Comment by nickrecchi** [comment]
Thanks for clearing that up @llaplant. Much appreciated.
