### ISSUE TITLE
Text version URLs for "Public Law" types

### ISSUE THREAD

**Issue by nickrecchi** [usgpo/bill-status#203]
Text versions with a "Public Law" type contain links that do not resolve, which I've been encountering since the recent 3.0.0 schema update (usgpo/bill-status#200).

Some bills that are impacted by this issue are:

**117hr4877**
Provided URL in BillStatus: https://www.govinfo.gov/content/pkg/PLAW-117publ188_uslm/xml/PLAW-117publ188_uslm.xml
Bulk Data URL: https://www.govinfo.gov/bulkdata/PLAW/117/public/PLAW-117publ188.xml

**117hr4693**
Provided URL in BillStatus: https://www.govinfo.gov/content/pkg/PLAW-117publ214_uslm/xml/PLAW-117publ214_uslm.xml
Bulk Data URL: https://www.govinfo.gov/bulkdata/PLAW/117/public/PLAW-117publ214.xml

**117hr468**
Provided URL in BillStatus: https://www.govinfo.gov/content/pkg/PLAW-117publ186_uslm/xml/PLAW-117publ186_uslm.xml
Bulk Data URL: https://www.govinfo.gov/bulkdata/PLAW/117/public/PLAW-117publ186.xml

**Comment by llaplant** [comment]
Updated and reprocessed. Example: 

https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr4877.xml points to https://www.govinfo.gov/content/pkg/PLAW-117publ188/uslm/PLAW-117publ188.xml
