### ISSUE TITLE
congress.gov access failure

### ISSUE THREAD

**Issue by rhurst6** [usgpo/bill-status#207]
Receiving upon trying to access congress.gov

Fatal error: Uncaught Exception: congress 118, 118 not found: 118 in /webapp/symfony/src/AppBundle/Service/Congress.php:380 Stack trace: #0 /webapp/symfony/src/AppBundle/Service/Congress.php(418): AppBundle\Service\Congress->getInfo('118', false) #1 /webapp/symfony/src/AppBundle/Service/Congress.php(395): AppBundle\Service\Congress->_ensureCurrentCongress(false) #2 /webapp/symfony/src/AppBundle/Service/Congress.php(308): AppBundle\Service\Congress->getCurrentCongressInfo(false) #3 /webapp/symfony/src/AppBundle/Service/BillStatusTracker.php(22): AppBundle\Service\Congress->getCurrentCongressId() #4 /webapp/symfony/var/cache/prod/ContainerSnexq6s/appProdDebugProjectContainer.php(1731): AppBundle\Service\BillStatusTracker->__construct(Object(AppBundle\Service\Congress)) #5 /webapp/symfony/var/cache/prod/ContainerSnexq6s/appProdDebugProjectContainer.php(2869): ContainerSnexq6s\appProdDebugProjectContainer->getBillStatusTrackerService() #6 /webapp/symfony/var/cache/prod/ContainerSnexq6s/appProdDebugProjectContainer.php(2121): in /webapp/symfony/src/AppBundle/Service/Congress.php on line 380

**Comment by llaplant** [comment]
Access was restored. Please see https://github.com/LibraryOfCongress/api.congress.gov.
