### ISSUE TITLE
Missing amendments in several bills

### ISSUE THREAD

**Issue by nickrecchi** [usgpo/bill-status#209]
Several bills contain an issue where the amendedAmendment is referencing an amendment that doesn't exist in the bill. I've been encountering this since the recent 3.0.0 schema update (usgpo/bill-status#200). The following bills have this issue:

- 117hr3684: Missing samdt 2137
- 117hr5376: Missing samdt 5194
- 117s1260: Missing samdt 1782
- 115hr2: Missing samdt 3176
- 115hr6147: Missing samdt 3399
- 115hconres71: Missing samdt 1116

**Comment by kboyd35** [comment]
<amendment> count seems to be limited to 250 even if there are more amendments. For example in 117HR5376, there should be 295 amendments, but there are only 250:
https://www.congress.gov/bill/117th-congress/house-bill/5376/amendments

117S1260 should have 616 amendments, but has 250.
https://www.congress.gov/bill/117th-congress/senate-bill/1260/amendments

**Comment by jonquandt** [comment]
Thanks for the additional examples.

**Comment by llaplant** [comment]
Updated and reprocessed. Examples:

https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr3684.xml

https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5376.xml
