### ISSUE TITLE
two CR pages for H5356 constitutional authority statement 

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#21]
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr5356.xml

has the following constitutional authority statement:

<constitutionalAuthorityStatementText>
<![CDATA[

<pre>From the Congressional Record Online through the Government Publishing Office [<a href='http://www.gpo.gov'>www.gpo.gov</a>]By Mr. BRADY of Texas:H.R. 5356.Congress has the power to enact this legislation pursuantto the following:Article 1, Section 8, Clause 7: ``The Congress shall havepower . . . to establish Post Offices and Post Roads.'' [PageH1802][Page H3296]</pre>

]]>
</constitutionalAuthorityStatementText>

I don't believe PageH1802 is correct.  Is this bad input data?

**Comment by llaplant** [comment]
Data in the BILLSTATUS XML file matches what is available in the Congressional Record PDF for the Constitutional Authority Statement for H.R. 5356 from the 114th Congress. https://www.govinfo.gov/content/pkg/CREC-2016-05-26/pdf/CREC-2016-05-26-pt1-PgH3296-10.pdf.
