### ISSUE TITLE
Introduced bills for 1/10 are not yet available in the Bill Status Bulk Data

### ISSUE THREAD

**Issue by boisvert1975** [usgpo/bill-status#210]
Introduced bills from yesterday are up on congress.gov but are not yet available in the bulk status feed.

For example:
https//www.congress.gov/bill/118th-congress/house-bill/230
https//www.congress.gov/bill/118th-congress/house-resolution/14
https//www.congress.gov/bill/118th-congress/house-joint-resolution/14

**Comment by gpo-billstatus** [comment]
Available now.

From: boisvert1975 ***@***.***>
Sent: Wednesday, January 11, 2023 11:14 AM
To: usgpo/bill-status ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [usgpo/bill-status] Introduced bills for 1/10 are not yet available in the Bill Status Bulk Data (Issue #210)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Introduced bills from yesterday are up on congress.gov but are not yet available in the bulk status feed.

For example:
https//www.congress.gov/bill/118th-congress/house-bill/230
https//www.congress.gov/bill/118th-congress/house-resolution/14
https//www.congress.gov/bill/118th-congress/house-joint-resolution/14

-
