### ISSUE TITLE
Bill Statuses for 117 H.R. 9705 through H.R. 9709 are missing

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#211]
Bill Statuses for H.R. 9705 through H.R. 9709 from the 117th Congress are missing from the bulk data repository.

They are up on congress.gov.

https://www.congress.gov/bill/117th-congress/house-bill/9705
https://www.congress.gov/bill/117th-congress/house-bill/9706
https://www.congress.gov/bill/117th-congress/house-bill/9707
https://www.congress.gov/bill/117th-congress/house-bill/9708
https://www.congress.gov/bill/117th-congress/house-bill/9709

**Comment by llaplant** [comment]
Files were processing and are now available. 

https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr9705.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr9706.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr9707.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr9708.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr9709.xml

**Comment by kboyd35** [comment]
I see them now. Thanks!
