### ISSUE TITLE
govinfo bill status files missing title

### ISSUE THREAD

**Issue by sun-yujia** [usgpo/bill-status#214]
Many bills introduced yesterday and today in the Bill Status collection in govinfo are missing a title. Examples include S542 and S562 but HRs are also affected. The <titles> tree and <title> tag found in other xml files are missing for the bills from yesterday and today. Can you add these fields back? 

Thank you!

**Comment by llaplant** [comment]
Bill Status is currently processing.

**Comment by jzheng-gpo** [comment]
Processing completed. Let us know if you still see issues.
