### ISSUE TITLE
Introduced bulls from 3/8 are not yet available in the Bill Status Bulk Data

### ISSUE THREAD

**Issue by boisvert1975** [usgpo/bill-status#215]
Introduced bills from yesterday are up on congress.gov but are no tyet available in he bulk status feed.

For example:
https://www.congress.gov/bill/118th-congress/1434 to 1477
https://www.congress.gov/bill/118th-congress/house-resolution/ 445 to 447 
https://www.congress.gov/bill/118th-congress/house-joint-resolution/41

**Comment by gpo-billstatus** [comment]
Thanks for reporting this issue.  We are in the process of pulling new data now. Will be available later.  Thanks.

From: boisvert1975 ***@***.***>
Sent: Thursday, March 9, 2023 11:52 AM
To: usgpo/bill-status ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [usgpo/bill-status] Introduced bulls from 3/8 are not yet available in the Bill Status Bulk Data (Issue #215)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Introduced bills from yesterday are up on congress.gov but are no tyet available in he bulk status feed.

For example:
https://www.congress.gov/bill/118th-congress/1434<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.congress.gov%2Fbill%2F118th-congress%2F1434&data=05%7C01%7Cazhang%40gpo.gov%7C6b7779fb31b749e00ffe08db20be88b4%7C97ae4de0d4584af3a7df1c19bdbe49d0%7C0%7C0%7C638139774952028852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ohcs1yL%2BiT2CrNxlFhidmYlyfVeJnMyphbenbMsqbk0%3D&reserved=0> to 1477
https://www.congress.gov/bill/118th-congress/house-resolution/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.congress.gov%2Fbill%2F118th-congress%2Fhouse-resolution%2F&data=05%7C01%7Cazhang%40gpo.gov%7C6b7779fb31b749e00ffe08db20be88b4%7C97ae4de0d4584af3a7df1c19bdbe49d0%7C0%7C0%7C638139774952028852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wmZOiWscxrweYVzmFqHGPW6nLLaJarIrU%2BE20qhasvY%3D&reserved=0> 445 to 447
https://www.congress.gov/bill/118th-congress/house-joint-resolution/41<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.congress.gov%2Fbill%2F118th-congress%2Fhouse-joint-resolution%2F41&data=05%7C01%7Cazhang%40gpo.gov%7C6b7779fb31b749e00ffe08db20be88b4%7C97ae4de0d4584af3a7df1c19bdbe49d0%7C0%7C0%7C638139774952028852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1tWNI%2BrQMtVueszWLKaFdIXwqzBXDzjEEohCOLkuLTc%3D&reserved=0>

-

**Comment by llaplant** [comment]
Bills are available.
