### ISSUE TITLE
Wrong Related Bill in 118 HR 29

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#216]
118 HR 696 is listed as a related bill in 118 HR 29.

https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr29.xml

The actual related bill should be 118 S 696.

**Comment by 104PL104** [comment]
@kboyd35 this has been fixed. Thank you!

**Comment by llaplant** [comment]
Reprocessed in GovInfo
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr29.xml
