### ISSUE TITLE
Introduced Bills from 6/7/2023 not available in bulk status feed

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#218]
Introduced bills from 6/7/2023 are up on congress.gov but are not yet available in he bulk status feed.

For example:
https://www.congress.gov/bill/118th-congress/house-bill/3934
https://www.congress.gov/bill/118th-congress/senate-bill/1870
https://www.congress.gov/bill/118th-congress/house-resolution/484
https://www.congress.gov/bill/118th-congress/senate-resolution/242

**Comment by gpo-billstatus** [comment]
They are available now.

From: kboyd35 ***@***.***>
Sent: Thursday, June 8, 2023 2:53 PM
To: usgpo/bill-status ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [usgpo/bill-status] Introduced Bills from 6/7/2023 not available in bulk status feed (Issue #218)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Introduced bills from 6/7/2023 are up on congress.gov but are not yet available in he bulk status feed.

For example:
https://www.congress.gov/bill/118th-congress/house-bill/3934
https://www.congress.gov/bill/118th-congress/senate-bill/1870
https://www.congress.gov/bill/118th-congress/house-resolution/484
https://www.congress.gov/bill/118th-congress/senate-resolution/242

-
