### ISSUE TITLE
Missing xml url data in BILLSTATUS'es

### ISSUE THREAD

**Issue by BorodaUA** [usgpo/bill-status#219]
Hello, 

I work with @aih on public projects related to bill and legislative data. In analyzing the GPO API, we have found packages that are missing certain information. The purpose of this issue is to document those packages where some information (typically `textVersions`) is missing from the GPO API.

Here are items where `BILLSTATUS` doesn't have a url for the package in `textVersions`. To confirm, open `BILLSTATUS URL` from the table below and search(Ctrl+F) for "textVersions" to see that the url is missing.
| BILLSTATUS ID| BILLSTATUS URL| Expected Package URL | Actual Package URL| Notes |
| :-------------: |:-------------:| :-------------:| :-------------:| :-------------:|
| 115hr5896| [115hr5896](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr5896.xml) | [115hr5896rh](https://api.govinfo.gov/packages/BILLS-115hr5896rh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr6762| [115hr6762](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr6762.xml) | [115hr6762ih](https://api.govinfo.gov/packages/BILLS-115hr6762ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr6389| [115hr6389](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr6389.xml) | [115hr6389ih](https://api.govinfo.gov/packages/BILLS-115hr6389ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr6342| [115hr6342](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr6342.xml) | [115hr6342ih](https://api.govinfo.gov/packages/BILLS-115hr6342ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr6176| [115hr6176](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr6176.xml) | [115hr6176ih](https://api.govinfo.gov/packages/BILLS-115hr6176ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr6063| [115hr6063](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr6063.xml) | [115hr6063ih](https://api.govinfo.gov/packages/BILLS-115hr6063ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 113hr1067| [113hr1067](http://www.govinfo.gov/bulkdata/BILLSTATUS/113/hr/BILLSTATUS-113hr1067.xml) | [113hr1067enr](https://api.govinfo.gov/packages/BILLS-113hr1067enr/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 113hr1068| [113hr1068](http://www.govinfo.gov/bulkdata/BILLSTATUS/113/hr/BILLSTATUS-113hr1068.xml) | [113hr1068enr](https://api.govinfo.gov/packages/BILLS-113hr1068enr/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr3241| [117hr3241](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr3241.xml) | [117hr3241rh](https://api.govinfo.gov/packages/BILLS-117hr3241rh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr3239| [117hr3239](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr3239.xml) | [117hr3239rh](https://api.govinfo.gov/packages/BILLS-117hr3239rh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr3241| [117hr3241](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr3241.xml) | [117hr3241rfs](https://api.govinfo.gov/packages/BILLS-117hr3241rfs/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr3241| [117hr3241](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr3241.xml) | [117hr3241eh](https://api.govinfo.gov/packages/BILLS-117hr3241eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr3239| [117hr3239](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr3239.xml) | [117hr3239rfs](https://api.govinfo.gov/packages/BILLS-117hr3239rfs/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr3239| [117hr3239](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr3239.xml) | [117hr3239eh](https://api.govinfo.gov/packages/BILLS-117hr3239eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5695| [117hr5695](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5695.xml) | [117hr5695ih](https://api.govinfo.gov/packages/BILLS-117hr5695ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5677| [117hr5677](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5677.xml) | [117hr5677ih](https://api.govinfo.gov/packages/BILLS-117hr5677ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5705| [117hr5705](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5705.xml) | [117hr5705ih](https://api.govinfo.gov/packages/BILLS-117hr5705ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5679| [117hr5679](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5679.xml) | [117hr5679ih](https://api.govinfo.gov/packages/BILLS-117hr5679ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5718| [117hr5718](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5718.xml) | [117hr5718ih](https://api.govinfo.gov/packages/BILLS-117hr5718ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5677| [117hr5677](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5677.xml) | [117hr5677rh](https://api.govinfo.gov/packages/BILLS-117hr5677rh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5695| [117hr5695](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5695.xml) | [117hr5695rh](https://api.govinfo.gov/packages/BILLS-117hr5695rh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5679| [117hr5679](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5679.xml) | [117hr5679eh](https://api.govinfo.gov/packages/BILLS-117hr5679eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5695| [117hr5695](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5695.xml) | [117hr5695eh](https://api.govinfo.gov/packages/BILLS-117hr5695eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5705| [117hr5705](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5705.xml) | [117hr5705eh](https://api.govinfo.gov/packages/BILLS-117hr5705eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5677| [117hr5677](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5677.xml) | [117hr5677eh](https://api.govinfo.gov/packages/BILLS-117hr5677eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5679| [117hr5679](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5679.xml) | [117hr5679rfs](https://api.govinfo.gov/packages/BILLS-117hr5679rfs/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5695| [117hr5695](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5695.xml) | [117hr5695rfs](https://api.govinfo.gov/packages/BILLS-117hr5695rfs/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5677| [117hr5677](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5677.xml) | [117hr5677rfs](https://api.govinfo.gov/packages/BILLS-117hr5677rfs/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 117hr5705| [117hr5705](http://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr5705.xml) | [117hr5705rfs](https://api.govinfo.gov/packages/BILLS-117hr5705rfs/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 116hres755| [116hres755](http://www.govinfo.gov/bulkdata/BILLSTATUS/116/hres/BILLSTATUS-116hres755.xml) | [116hres755eh](https://api.govinfo.gov/packages/BILLS-116hres755eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr5295| [115hr5295](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr5295.xml) | [115hr5295ih](https://api.govinfo.gov/packages/BILLS-115hr5295ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr5293| [115hr5293](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr5293.xml) | [115hr5293ih](https://api.govinfo.gov/packages/BILLS-115hr5293ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr5297| [115hr5297](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr5297.xml) | [115hr5297ih](https://api.govinfo.gov/packages/BILLS-115hr5297ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr5296| [115hr5296](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr5296.xml) | [115hr5296ih](https://api.govinfo.gov/packages/BILLS-115hr5296ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr5344| [115hr5344](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr5344.xml) | [115hr5344ih](https://api.govinfo.gov/packages/BILLS-115hr5344ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 115hr1625| [115hr1625](http://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr1625.xml) | [115hr1625eah](https://api.govinfo.gov/packages/BILLS-115hr1625eah/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 114hr2832| [114hr2832](http://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr2832.xml) | [114hr2832ih](https://api.govinfo.gov/packages/BILLS-114hr2832ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 114hr2834| [114hr2834](http://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr2834.xml) | [114hr2834ih](https://api.govinfo.gov/packages/BILLS-114hr2834ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 114hr2831| [114hr2831](http://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr2831.xml) | [114hr2831ih](https://api.govinfo.gov/packages/BILLS-114hr2831ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 114hr2830| [114hr2830](http://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr2830.xml) | [114hr2830ih](https://api.govinfo.gov/packages/BILLS-114hr2830ih/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 114hr2832| [114hr2832](http://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr2832.xml) | [114hr2832eh](https://api.govinfo.gov/packages/BILLS-114hr2832eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 114hr2831| [114hr2831](http://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr2831.xml) | [114hr2831eh](https://api.govinfo.gov/packages/BILLS-114hr2831eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 114hr2830| [114hr2830](http://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr2830.xml) | [114hr2830eh](https://api.govinfo.gov/packages/BILLS-114hr2830eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 114hr2831| [114hr2831](http://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr2831.xml) | [114hr2831rfs](https://api.govinfo.gov/packages/BILLS-114hr2831rfs/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 114hr2830| [114hr2830](http://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr2830.xml) | [114hr2830rfs](https://api.govinfo.gov/packages/BILLS-114hr2830rfs/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 114hr2832| [114hr2832](http://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr2832.xml) | [114hr2832rfs](https://api.govinfo.gov/packages/BILLS-114hr2832rfs/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 118sres77| [118sres77](http://www.govinfo.gov/bulkdata/BILLSTATUS/118/sres/BILLSTATUS-118sres77.xml) | [118sres77ats](https://api.govinfo.gov/packages/BILLS-118sres77ats/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |
| 118hres383| [118hres383](http://www.govinfo.gov/bulkdata/BILLSTATUS/118/hres/BILLSTATUS-118hres383.xml) | [118hres383eh](https://api.govinfo.gov/packages/BILLS-118hres383eh/xml?api_key=DEMO_KEY) | None| The url for this version is missing from BILLSTATUS in `textVersions>formats` |

**Comment by jonquandt** [comment]
Good afternoon -- 

I have done some checking and can confirm that there is no XML available for any of the BILLS packages in your list. This means that GovInfo did not receive XML at the time of ingest of those packages. I don't have any specific reasons why those bills may not have XML, but that may be something that House Staff can help determine. 

The BILLS ID field links to the API package summary, where you can see the available downloadable content.


BILLSTATUS ID | BILLS ID | XML Exists? | Congress | Bill Type | Bill Number | Bill Version | Title
-- | -- | -- | -- | -- | -- | -- | --
BILLSTATUS-115hr5896 | [BILLS-115hr5896rh](https://api.govinfo.gov/packages/BILLS-115hr5896rh/summary?api_key=DEMO_KEY') | No | 115 | hr | 5896 | rh | To amend title 5, United States Code, to modify the authority for pay and   work schedules of border patrol agents, and for other purposes.
BILLSTATUS-115hr6762 | [BILLS-115hr6762ih](https://api.govinfo.gov/packages/BILLS-115hr6762ih/summary?api_key=DEMO_KEY') | No | 115 | hr | 6762 | ih | H.R. 6762 (IH) - Introduced in House
BILLSTATUS-115hr6389 | [BILLS-115hr6389ih](https://api.govinfo.gov/packages/BILLS-115hr6389ih/summary?api_key=DEMO_KEY') | No | 115 | hr | 6389 | ih | H.R. 6389 (IH) - Introduced in House
BILLSTATUS-115hr6342 | [BILLS-115hr6342ih](https://api.govinfo.gov/packages/BILLS-115hr6342ih/summary?api_key=DEMO_KEY') | No | 115 | hr | 6342 | ih | H.R. 6342 (IH) - Introduced in House
BILLSTATUS-115hr6176 | [BILLS-115hr6176ih](https://api.govinfo.gov/packages/BILLS-115hr6176ih/summary?api_key=DEMO_KEY') | No | 115 | hr | 6176 | ih | H.R. 6176 (IH) - Introduced in House
BILLSTATUS-115hr6063 | [BILLS-115hr6063ih](https://api.govinfo.gov/packages/BILLS-115hr6063ih/summary?api_key=DEMO_KEY') | No | 115 | hr | 6063 | ih | H.R. 6063 (IH) - Introduced in House
BILLSTATUS-113hr1067 | [BILLS-113hr1067enr](https://api.govinfo.gov/packages/BILLS-113hr1067enr/summary?api_key=DEMO_KEY') | No | 113 | hr | 1067 | enr | An act h.R. 1067 (ENR) - Enrolled Bill"
BILLSTATUS-113hr1068 | [BILLS-113hr1068enr](https://api.govinfo.gov/packages/BILLS-113hr1068enr/summary?api_key=DEMO_KEY') | No | 113 | hr | 1068 | enr | An act h.R. 1068 (ENR) - Enrolled Bill"
BILLSTATUS-117hr3241 | [BILLS-117hr3241rh](https://api.govinfo.gov/packages/BILLS-117hr3241rh/summary?api_key=DEMO_KEY') | No | 117 | hr | 3241 | rh | To make improvements in the enactment of title 54, United States Code,   into a positive law title and to improve the Code.
BILLSTATUS-117hr3239 | [BILLS-117hr3239rh](https://api.govinfo.gov/packages/BILLS-117hr3239rh/summary?api_key=DEMO_KEY') | No | 117 | hr | 3239 | rh | To make improvements in the enactment of title 41, United States Code,   into a positive law title and to improve the Code.
BILLSTATUS-117hr3241 | [BILLS-117hr3241rfs](https://api.govinfo.gov/packages/BILLS-117hr3241rfs/summary?api_key=DEMO_KEY') | No | 117 | hr | 3241 | rfs | An act h.R. 3241 (RFS) - Referred in Senate"
BILLSTATUS-117hr3241 | [BILLS-117hr3241eh](https://api.govinfo.gov/packages/BILLS-117hr3241eh/summary?api_key=DEMO_KEY') | No | 117 | hr | 3241 | eh | An act to make improvements in the enactment of title 54, United States   Code, into a positive law title and to improve the Code.
BILLSTATUS-117hr3239 | [BILLS-117hr3239rfs](https://api.govinfo.gov/packages/BILLS-117hr3239rfs/summary?api_key=DEMO_KEY') | No | 117 | hr | 3239 | rfs | An act h.R. 3239 (RFS) - Referred in Senate"
BILLSTATUS-117hr3239 | [BILLS-117hr3239eh](https://api.govinfo.gov/packages/BILLS-117hr3239eh/summary?api_key=DEMO_KEY') | No | 117 | hr | 3239 | eh | An act to make improvements in the enactment of title 41, United States   Code, into a positive law title and to improve the Code.
BILLSTATUS-117hr5695 | [BILLS-117hr5695ih](https://api.govinfo.gov/packages/BILLS-117hr5695ih/summary?api_key=DEMO_KEY') | No | 117 | hr | 5695 | ih | H.R. 5695 (IH) - Introduced in House
BILLSTATUS-117hr5677 | [BILLS-117hr5677ih](https://api.govinfo.gov/packages/BILLS-117hr5677ih/summary?api_key=DEMO_KEY') | No | 117 | hr | 5677 | ih | H.R. 5677 (IH) - Introduced in House
BILLSTATUS-117hr5705 | [BILLS-117hr5705ih](https://api.govinfo.gov/packages/BILLS-117hr5705ih/summary?api_key=DEMO_KEY') | No | 117 | hr | 5705 | ih | H.R. 5705 (IH) - Introduced in House
BILLSTATUS-117hr5679 | [BILLS-117hr5679ih](https://api.govinfo.gov/packages/BILLS-117hr5679ih/summary?api_key=DEMO_KEY') | No | 117 | hr | 5679 | ih | H.R. 5679 (IH) - Introduced in House
BILLSTATUS-117hr5718 | [BILLS-117hr5718ih](https://api.govinfo.gov/packages/BILLS-117hr5718ih/summary?api_key=DEMO_KEY') | No | 117 | hr | 5718 | ih | Prince Congressional Gold Medal Act"
BILLSTATUS-117hr5677 | [BILLS-117hr5677rh](https://api.govinfo.gov/packages/BILLS-117hr5677rh/summary?api_key=DEMO_KEY') | No | 117 | hr | 5677 | rh | To make technical amendments to update statutory references to certain   provisions classified to title 2, United States Code, title 50, United States   Code, and title 52, United States Code.
BILLSTATUS-117hr5695 | [BILLS-117hr5695rh](https://api.govinfo.gov/packages/BILLS-117hr5695rh/summary?api_key=DEMO_KEY') | No | 117 | hr | 5695 | rh | To make technical amendments to update statutory references to certain   provisions which were formerly classified to chapters 14 and 19 of title 25,   United States Code.
BILLSTATUS-117hr5679 | [BILLS-117hr5679eh](https://api.govinfo.gov/packages/BILLS-117hr5679eh/summary?api_key=DEMO_KEY') | No | 117 | hr | 5679 | eh | An act to make technical amendments to update statutory references to   certain provisions classified to title 7, title 20, and title 43, United   States Code.
BILLSTATUS-117hr5695 | [BILLS-117hr5695eh](https://api.govinfo.gov/packages/BILLS-117hr5695eh/summary?api_key=DEMO_KEY') | No | 117 | hr | 5695 | eh | An act to make technical amendments to update statutory references to   certain provisions which were formerly classified to chapters 14 and 19 of   title 25, United States Code.
BILLSTATUS-117hr5705 | [BILLS-117hr5705eh](https://api.govinfo.gov/packages/BILLS-117hr5705eh/summary?api_key=DEMO_KEY') | No | 117 | hr | 5705 | eh | An act to make technical amendments to update statutory references to   provisions reclassified to title 34, United States Code.
BILLSTATUS-117hr5677 | [BILLS-117hr5677eh](https://api.govinfo.gov/packages/BILLS-117hr5677eh/summary?api_key=DEMO_KEY') | No | 117 | hr | 5677 | eh | An act to make technical amendments to update statutory references to   certain provisions classified to title 2, United States Code, title 50,   United States Code, and title 52, United States Code.
BILLSTATUS-117hr5679 | [BILLS-117hr5679rfs](https://api.govinfo.gov/packages/BILLS-117hr5679rfs/summary?api_key=DEMO_KEY') | No | 117 | hr | 5679 | rfs | An act h.R. 5679 (RFS) - Referred in Senate"
BILLSTATUS-117hr5695 | [BILLS-117hr5695rfs](https://api.govinfo.gov/packages/BILLS-117hr5695rfs/summary?api_key=DEMO_KEY') | No | 117 | hr | 5695 | rfs | An act h.R. 5695 (RFS) - Referred in Senate"
BILLSTATUS-117hr5677 | [BILLS-117hr5677rfs](https://api.govinfo.gov/packages/BILLS-117hr5677rfs/summary?api_key=DEMO_KEY') | No | 117 | hr | 5677 | rfs | An act h.R. 5677 (RFS) - Referred in Senate"
BILLSTATUS-117hr5705 | [BILLS-117hr5705rfs](https://api.govinfo.gov/packages/BILLS-117hr5705rfs/summary?api_key=DEMO_KEY') | No | 117 | hr | 5705 | rfs | An act h.R. 5705 (RFS) - Referred in Senate"
BILLSTATUS-116hres755 | [BILLS-116hres755eh](https://api.govinfo.gov/packages/BILLS-116hres755eh/summary?api_key=DEMO_KEY') | No | 116 | hres | 755 | eh | H. RES. 755 (EH) - Engrossed in House"
BILLSTATUS-115hr5295 | [BILLS-115hr5295ih](https://api.govinfo.gov/packages/BILLS-115hr5295ih/summary?api_key=DEMO_KEY') | No | 115 | hr | 5295 | ih | H.R. 5295 (IH) - Introduced in House
BILLSTATUS-115hr5293 | [BILLS-115hr5293ih](https://api.govinfo.gov/packages/BILLS-115hr5293ih/summary?api_key=DEMO_KEY') | No | 115 | hr | 5293 | ih | H.R. 5293 (IH) - Introduced in House
BILLSTATUS-115hr5297 | [BILLS-115hr5297ih](https://api.govinfo.gov/packages/BILLS-115hr5297ih/summary?api_key=DEMO_KEY') | No | 115 | hr | 5297 | ih | H.R. 5297 (IH) - Introduced in House
BILLSTATUS-115hr5296 | [BILLS-115hr5296ih](https://api.govinfo.gov/packages/BILLS-115hr5296ih/summary?api_key=DEMO_KEY') | No | 115 | hr | 5296 | ih | H.R. 5296 (IH) - Introduced in House
BILLSTATUS-115hr5344 | [BILLS-115hr5344ih](https://api.govinfo.gov/packages/BILLS-115hr5344ih/summary?api_key=DEMO_KEY') | No | 115 | hr | 5344 | ih | H.R. 5344 (IH) - Introduced in House
BILLSTATUS-115hr1625 | [BILLS-115hr1625eah](https://api.govinfo.gov/packages/BILLS-115hr1625eah/summary?api_key=DEMO_KEY') | No | 115 | hr | 1625 | eah | An Act to amend the State Department Basic Authorities Act of 1956 to   include severe forms of trafficking in persons within the definition of   transnational organized crime for purposes of the rewards program of the   Department of State, and for other purposes.
BILLSTATUS-114hr2832 | [BILLS-114hr2832ih](https://api.govinfo.gov/packages/BILLS-114hr2832ih/summary?api_key=DEMO_KEY') | No | 114 | hr | 2832 | ih | H.R. 2832 (IH) - Introduced in House
BILLSTATUS-114hr2834 | [BILLS-114hr2834ih](https://api.govinfo.gov/packages/BILLS-114hr2834ih/summary?api_key=DEMO_KEY') | No | 114 | hr | 2834 | ih | H.R. 2834 (IH) - Introduced in House
BILLSTATUS-114hr2831 | [BILLS-114hr2831ih](https://api.govinfo.gov/packages/BILLS-114hr2831ih/summary?api_key=DEMO_KEY') | No | 114 | hr | 2831 | ih | H.R. 2831 (IH) - Introduced in House
BILLSTATUS-114hr2830 | [BILLS-114hr2830ih](https://api.govinfo.gov/packages/BILLS-114hr2830ih/summary?api_key=DEMO_KEY') | No | 114 | hr | 2830 | ih | To make technical amendments to update statutory references to certain   provisions classified to title 2, United States Code
BILLSTATUS-114hr2832 | [BILLS-114hr2832eh](https://api.govinfo.gov/packages/BILLS-114hr2832eh/summary?api_key=DEMO_KEY') | No | 114 | hr | 2832 | eh | An act to make technical amendments to update statutory references to   certain provisions classified to title 52, United States Code.
BILLSTATUS-114hr2831 | [BILLS-114hr2831eh](https://api.govinfo.gov/packages/BILLS-114hr2831eh/summary?api_key=DEMO_KEY') | No | 114 | hr | 2831 | eh | An act to make technical amendments to update statutory references to   provisions classified to chapters 44, 45, 46, and 47 of title 50, United   States Code.
BILLSTATUS-114hr2830 | [BILLS-114hr2830eh](https://api.govinfo.gov/packages/BILLS-114hr2830eh/summary?api_key=DEMO_KEY') | No | 114 | hr | 2830 | eh | An act to make technical amendments to update statutory references to   certain provisions classified to title 2, United States Code.
BILLSTATUS-114hr2831 | [BILLS-114hr2831rfs](https://api.govinfo.gov/packages/BILLS-114hr2831rfs/summary?api_key=DEMO_KEY') | No | 114 | hr | 2831 | rfs | An act h.R. 2831 (RFS) - Referred in Senate"
BILLSTATUS-114hr2830 | [BILLS-114hr2830rfs](https://api.govinfo.gov/packages/BILLS-114hr2830rfs/summary?api_key=DEMO_KEY') | No | 114 | hr | 2830 | rfs | An act h.R. 2830 (RFS) - Referred in Senate"
BILLSTATUS-114hr2832 | [BILLS-114hr2832rfs](https://api.govinfo.gov/packages/BILLS-114hr2832rfs/summary?api_key=DEMO_KEY') | No | 114 | hr | 2832 | rfs | An act h.R. 2832 (RFS) - Referred in Senate"
BILLSTATUS-118sres77 | [BILLS-118sres77ats](https://api.govinfo.gov/packages/BILLS-118sres77ats/summary?api_key=DEMO_KEY') | No | 118 | sres | 77 | ats | S. RES. 77 (ATS) - Agreed to Senate"
BILLSTATUS-118hres383 | [BILLS-118hres383eh](https://api.govinfo.gov/packages/BILLS-118hres383eh/summary?api_key=DEMO_KEY') | No | 118 | hres | 383 | eh | H. RES. 383 (EH) - Engrossed in House"

**Comment by aih** [comment]
Thank you so much for undertaking this review, @jonquandt! For downstream tools, and users it is very helpful to confirm that the XML is missing for particular documents. We'll do some investigation about these to see, e.g. if there is a pattern for these (e.g. some appear to be technical amendments).

**Comment by jonquandt** [comment]
@aih - happy to help!

A potential alternative would be to use the related endpoint against given BILLSTATUS package IDs to determine which bill text versions exist and then grab the xmlLink if available. I assume the html/text wouldn't be useful for you, but that could be an alternative format.

- Collections request for new/updated BILLSTATUS
- Follow each packageLink to go to the summary
- on package summary, fetch the xmlLink to get the BILLSTATUS XML AND
- On same package summary, follow the related link to get the list of relationships, including bill text - like https://api.govinfo.gov/related/BILLSTATUS-115hr5896?api_key=DEMO_KEY
- follow the relationshipLink associated with BILLS - e.g. https://api.govinfo.gov/related/BILLSTATUS-115hr5896/BILLS?api_key=DEMO_KEY
- this will provide a list of bill packages, with packageLinks that you can follow to get the available download formats (as in the table above)

That presumably is less efficient from a request perspective than just getting the BILLSTATUS xml and pull text versions, but then you would be sure that the xml is actually available or not.

That being said, the upstream Congress.gov API that our BILLSTATUS xml relies on uses our API to grab bill information, so if an xml textVersion doesn't exist for a bill, that will generally be because it does not exist on GovInfo.

-

**Comment by aih** [comment]
I think this is the sequence we used to follow, but the Billstatus -> textversion sequence is so much more efficient (I think that was one of the later improvements in the API). We now have a number of years of examples (above) that you've confirmed that the missing `textVersion` means the xml is missing. I think we'll take that as the indicator for now (but we'll still make some inquiries why these bills are missing xml).

**Comment by jonquandt** [comment]
Totally fair.

Thinking about it more, If any other textVesion formats exist - e.g. pdf or html, that's a good indicator that the package exists on GovInfo, but that we don't have the XML.
