### ISSUE TITLE
truncated subcommittee name

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#22]
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s189.xml

The subcommittee name appears to be truncated:

<name>and Federal Management Subcommittee</name>

<committees>
<billCommittees>
<item>
<name>
Homeland Security and Governmental Affairs Committee
</name>
<systemCode>ssga00</systemCode>
<chamber>Senate</chamber>
<activities>
<item>
<name>Referred to</name>
<date>2015-01-20T16:33:00Z</date>
</item>
</activities>
<type>Standing</type>
<subcommittees>
<item>
<activities>
<item>
<name>Hearings by</name>
<date>2016-02-24T15:34:08Z</date>
</item>
</activities>
<systemCode>ssga19</systemCode>
<name>and Federal Management Subcommittee</name>
</item>
</subcommittees>
</item>
</billCommittees>
</committees>

**Comment by llaplant** [comment]
Regulatory Affairs and Federal Management Subcommittee
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s189.xml
