### ISSUE TITLE
Related Bill listed on congress.gov but not in Bulk Status

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#222]
In HR1118 on congress.gov HR 11 is listed as a related bill:

https://www.congress.gov/bill/118th-congress/house-bill/1118/related-bills

However it is not listed in the bulk status version of the bill:

https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr1118.xml

**Comment by llaplant** [comment]
Refreshing Bill Status Bulk Data from Congress.gov source. I'll let you know when it is updated.

**Comment by gpo-billstatus** [comment]
It is available now.  https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr1118.xml


From: kboyd35 ***@***.***>
Sent: Thursday, August 31, 2023 10:20 AM
To: usgpo/bill-status ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [usgpo/bill-status] Related Bill listed on congress.gov but not in Bulk Status (Issue #222)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



In HR1118 on congress.gov HR 11 is listed as a related bill:

https://www.congress.gov/bill/118th-congress/house-bill/1118/related-bills

However it is not listed in the bulk status version of the bill:

https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr1118.xml

-
