### ISSUE TITLE
Missing Senate recorded votes in several bills

### ISSUE THREAD

**Issue by nickrecchi** [usgpo/bill-status#223]
Several bills contain an issue where the action item does not contain the Senate recordedVotes. To confirm these votes exist, I verified they existed in older BillStatus files from before the change to move recordedVotes to actions in the 3.0.0 schema update (usgpo/bill-status#200), or I compared the recordedVotes in the most recent BillStatus files against https://www.congress.gov/ and https://www.senate.gov/. 

Some bills that are impacted by this issue are:

- 118s316: Missing Senate roll numbers 61, 63, 70; Does contain Senate roll number 77
- 117hr7691: Missing Senate roll numbers 177, 178, 190; Does contain Senate roll number 191
- 116s1: Missing Senate roll numbers 1, 2, 3, 11, 12, 15; Does contain Senate roll number 16
- 115hr695: Missing Senate roll numbers 29, 274

**Comment by jonquandt** [comment]
@nickrecchi 

We have completed a deployment that addresses this issue going forward. I have also reprocessed the examples that you provided and verified that the missing votes appear to be visible now. In order for this to be a comprehensive fix, we will be reprocessing our entire BILLSTATUS dataset in the coming weeks.

Feel free to take a look at the examples you provided and let me know if you see any further issues.
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/s/BILLSTATUS-118s316.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr7691.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/s/BILLSTATUS-116s1.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr695.xml

**Comment by nickrecchi** [comment]
@jonquandt I reviewed the examples I provided, and all of them now have the votes that were previously missing. Glad this has been fixed and the BILLSTATUS dataset will be reprocessed. Thank you.

**Comment by jonquandt** [comment]
All BILLSTATUS packages have been reprocessed to address this issue.
