### ISSUE TITLE
114hr636 not updated after getting a public law number

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#23]
For HR 636, [Congress.gov shows](https://www.congress.gov/bill/114th-congress/house-bill/636):

    Latest Action:	07/15/2016 Became Public Law No: 114-190.  

(The actions detail page isn't working this morning so I can't see the full action history.)

The latest action in [the XML](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr636.xml) is missing that information:

    <actionDate>2016-07-14</actionDate>
    <text>Presented to President.</text>

After 5 days, OFR still hasn't published the public law number on [their website](https://www.archives.gov/federal-register/laws/current.html). (How do we get them CC'd on this issue?)

But if Congress.gov knows about it, I would expect it to be in the XML, so I'm flagging that as an issue here.

**Comment by 104PL104** [comment]
There were data exchange issues from Sunday through yesterday that likely prevented the new data from getting into the XML. Issues are reported to be resolved.

**Comment by 104PL104** [comment]
Law numbers get into Congress.gov quickly due to manual, human curation.

**Comment by JoshData** [comment]
And yet the XML is still not updated.

Would appreciate if you could leave issues like these open until the published XML is correct.

**Comment by llaplant** [comment]
We are catching up the XML from recent data exchange issues. Will try to bump this one up in the queue.

**Comment by JoshData** [comment]
Thanks.

**Comment by llaplant** [comment]
The latest action in [the XML](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr636.xml) has been updated. 
<actionDate>2016-07-14</actionDate>
<text>Presented to President.</text>

**Comment by JoshData** [comment]
Thanks.

Looks like it has a duplicate action entry (the 1st and the 3rd both are "Became Public Law No: 114-190." with source system = LoC).

**Comment by llaplant** [comment]
1st entry has actionCode E40000 and type President. 
3rd entry has actionCode 36000 and type BecameLaw. 
Values for code, name, and text are the same.

**Comment by JoshData** [comment]
Interesting.....
