### ISSUE TITLE
Recent House roll call vote URLs

### ISSUE THREAD

**Issue by nickrecchi** [usgpo/bill-status#233]
Recently updated Bill Status files contain House roll call vote links that do not resolve. The correct URLs contain the number 0 prior to the roll call number, as shown in these examples:

**118hr886**
Provided URL: https://clerk.house.gov/evs/2024/roll80.xml
Correct URL: https://clerk.house.gov/evs/2024/roll080.xml

**118hr1752**
Provided URL: https://clerk.house.gov/evs/2024/roll79.xml
Correct URL: https://clerk.house.gov/evs/2024/roll079.xml

**118hr6276**
Provided URL: https://clerk.house.gov/evs/2024/roll84.xml
Correct URL: https://clerk.house.gov/evs/2024/roll084.xml

**118hr7521**
Provided URL: https://clerk.house.gov/evs/2024/roll86.xml
Correct URL: https://clerk.house.gov/evs/2024/roll086.xml

**118hres1065**
Provided URL: https://clerk.house.gov/evs/2024/roll85.xml
Correct URL: https://clerk.house.gov/evs/2024/roll085.xml

**118hres1071**
Provided URL: https://clerk.house.gov/evs/2024/roll82.xml
Correct URL: https://clerk.house.gov/evs/2024/roll082.xml

**Comment by llaplant** [comment]
Issue is present in Congress.gov API response and tracked at https://github.com/LibraryOfCongress/api.congress.gov/issues/210

**Comment by nickrecchi** [comment]
The way this impacts single digit roll call numbers is that the correct URL has 2 0s prior to the roll call number.

118hres947:
Provided URL: https://clerk.house.gov/evs/2024/roll2.xml
Correct URL: https://clerk.house.gov/evs/2024/roll002.xml

**Comment by apreiter18** [comment]
Congress.gov API issue has been resolved (see https://github.com/LibraryOfCongress/api.congress.gov/issues/210)

**Comment by llaplant** [comment]
As a next step, GPO will need to reprocess impacted BILLSTATUS 118.

**Comment by llaplant** [comment]
BILLSTATUS 118 was reprocessed.
