### ISSUE TITLE
Bills from 4/17 not available yet

### ISSUE THREAD

**Issue by melissa337** [usgpo/bill-status#236]
Hi, we do not see the following bills from 4/16 in the XML file. Thank!

https://www.congress.gov/bill/118th-congress/house-bill/8034
https://www.congress.gov/bill/118th-congress/house-bill/8035
https://www.congress.gov/bill/118th-congress/house-bill/8036

**Comment by gpo-billstatus** [comment]
Available now. Thanks.

From: Melissa Wood ***@***.***>
Sent: Friday, April 19, 2024 9:00 AM
To: usgpo/bill-status ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [usgpo/bill-status] Bills from 4/17 not available yet (Issue #236)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi, we do not see the following bills from 4/16 in the XML file. Thank!

https://www.congress.gov/bill/118th-congress/house-bill/8034
https://www.congress.gov/bill/118th-congress/house-bill/8035
https://www.congress.gov/bill/118th-congress/house-bill/8036

-

**Comment by jzheng-gpo** [comment]
I saw below:
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr8060.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr8081.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr8105.xml


From: kboyd35 ***@***.***>
Sent: Monday, April 22, 2024 10:29 AM
To: usgpo/bill-status ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] Re: [usgpo/bill-status] Bills from 4/17 not available yet (Issue #236)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Bills from 4/18 , 4/19, and 4/20 are not available now. For example:
https://www.congress.gov/bill/118th-congress/house-bill/8060
https://www.congress.gov/bill/118th-congress/house-bill/8081
https://www.congress.gov/bill/118th-congress/house-bill/8105

-
