### ISSUE TITLE
Missing Signed by President actions

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#237]
Hi all. For [S. 992](https://www.congress.gov/bill/118th-congress/senate-bill/992/all-actions) and [H.R. 2882](https://www.congress.gov/bill/118th-congress/house-bill/2882/all-actions), the usual _Signed by President_ actions are missing. I think they might have been there originally and disappeared.

**Comment by llaplant** [comment]
Hi Josh, we'll take a look.

**Comment by JoshData** [comment]
TY!

**Comment by JoshData** [comment]
Thanks!
