### ISSUE TITLE
Missing amendments in bill status that are available on congress.gov

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#239]
In 118 S 4638 there are 1119 amendments on congress.gov:
https://www.congress.gov/bill/118th-congress/senate-bill/4638/amendments

but only 1100 amendments in the bulk status feed:
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/s/BILLSTATUS-118s4638.xml

**Comment by jzheng-gpo** [comment]
Will refresh soon

**Comment by kboyd35** [comment]
I'm still not seeing this status file being updated:
![image](https://github.com/user-attachments/assets/1bc1cc03-0129-42e1-83f3-afeb2d209a2f)

**Comment by jzheng-gpo** [comment]
The update takes time because of the size of amendments.  I will update you once complete.

**Comment by jzheng-gpo** [comment]
Refreshed with 1119 amendments now.
