### ISSUE TITLE
missing sponsor information

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#24]
Some bills are coming up without sponsor info.

One is [114s2874](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s2874.xml), which has an empty sponsors node:

    <sponsors/>

although it [has a sponsor on Congress.gov](https://www.congress.gov/bill/114th-congress/senate-bill/2874).

Also showing the same issue: s2883, s3160, s3231, s3232, s3278, sres515, sres522, sres532, sres533, and sres543.

**Comment by llaplant** [comment]
Reprocessing. Will let you know when complete.

**Comment by llaplant** [comment]
Completed around 4:45.

**Comment by JoshData** [comment]
Thanks!

**Comment by JoshData** [comment]
There's a new batch with the same issue, including s2658.

**Comment by llaplant** [comment]
I want to see if the data is updated with the noon job. Am thinking this may be related to timing.

**Comment by llaplant** [comment]
[BILLSTATUS-114s2658](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s2658.xml) was reprocessed 3 times today at 8/11/2016 4:07:10 AM, 8/11/2016 8:09:57 AM, and 8/11/2016 12:17:31 PM. Sponsors were added with the noon job.

**Comment by JoshData** [comment]
Great! Thanks.
