### ISSUE TITLE
recordedVotes xml links look badly formatted (missing 0 padding)

### ISSUE THREAD

**Issue by jerusalemmoorework** [usgpo/bill-status#240]
While processing bulk bill data and subsequent voting record data I noticed a failure due to a badly formatted link in some entries.

ex 
this entry
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr400.xml

includes this link in a recordedVotes element
https://clerk.house.gov/evs/2023/roll35.xml

the above link is dead and looks like it should actually be 
https://clerk.house.gov/evs/2023/roll035.xml

it looks like the links should be formatted with 0 padding but aren't when included in entries like
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr400.xml

**Comment by llaplant** [comment]
Issue is present in Congress.gov API response data. GPO is coordinating with the Library of Congress Congress.gov Team.  See also https://github.com/LibraryOfCongress/api.congress.gov.

**Comment by llaplant** [comment]
Verified fix in https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr400.xml. GPO will plan a reprocess of 118 BILLSTATUS to pick up fixes to any additional 118 BILLSTATUS files.

**Comment by jerusalemmoorework** [comment]
Thanks team

**Comment by llaplant** [comment]
Reprocessing 118 BILLSTATUS is finished. Closing issue. Thanks!
