### ISSUE TITLE
Missing Signed by President actions (take two)

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#244]
Similar to #237, there are a few bills that have action lines for becoming enacted but no Signed by President action, all on Sept. 26:

https://www.congress.gov/bill/118th-congress/house-bill/9747/all-actions
https://www.congress.gov/bill/118th-congress/senate-bill/265/all-actions
https://www.congress.gov/bill/118th-congress/senate-bill/1648/all-actions
https://www.congress.gov/bill/118th-congress/senate-bill/4351/all-actions

Thanks.

**Comment by 104PL104** [comment]
We are investigating and will report back soon. Thank you for reporting these.

**Comment by 104PL104** [comment]
The issue has been resolved. Please verify or close the ticket.

**Comment by JoshData** [comment]
Looks good, thanks!

**Comment by JoshData** [comment]
Hijacking this for another similar issue. In this bill, it's Signed by President after it Became Public Law. I think the date on the latter is incorrect based on the NARA table.

https://www.govinfo.gov/bulkdata/BILLSTATUS/118/s/BILLSTATUS-118s3960.xml
https://www.archives.gov/federal-register/laws/current.html

**Comment by llaplant** [comment]
Hi Josh, sent to Congress.gov Team since BILLSTATUS bulk data file is consistent with Congress.gov API response. https://api.congress.gov/v3/bill/118/s/3960/actions?api_key=DEMO_KEY

**Comment by apreiter18** [comment]
@JoshData, @llaplant -

We have received the update and the CDG API now reflects this. Please let me know if you have any questions. Thanks!

**Comment by llaplant** [comment]
@JoshData -- Update in Bill Status Bulk Data XML
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/s/BILLSTATUS-118s3960.xml

**Comment by JoshData** [comment]
TY!
