### ISSUE TITLE
subjects moved around in in 114hr5714 (and others)

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#25]
In [114hr5714](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr5714.xml) and three other files, the subjects have moved around and don't match the documented format.

![image](https://cloud.githubusercontent.com/assets/445875/18065590/7331be58-6e02-11e6-8c8e-be6339eb754b.png)

^ should not look anything like that.

**Comment by 104PL104** [comment]
https://github.com/usgpo/bill-status/blob/master/CHANGELOG.md

Adjusted subjects elements are better aligned with https://www.congress.gov/help/field-values/policy-area and https://www.congress.gov/help/field-values/legislative-subject-terms. Get background about subject terms from https://www.congress.gov/help/faq/find-bills-by-subject

**Comment by JoshData** [comment]
Please please come up with a versioning policy that's not "we'll post the changelog after your site breaks".

**Comment by JoshData** [comment]
As in #23, I would appreciate it if you could leave issues like these open until (all) the published XML is correct (in this case, until all published files match the new schema). h/t @pqnelson  (https://github.com/unitedstates/congress/issues/180#issuecomment-247375930)

**Comment by llaplant** [comment]
We'll begin reprocessing 113 today.

**Comment by JoshData** [comment]
Thanks.

**Comment by JoshData** [comment]
Looks like [114sres259](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/sres/BILLSTATUS-114sres259.xml) has reverted back to the old schema. See the referenced issue above this comment for more details. h/t @krues8dr

**Comment by llaplant** [comment]
Reprocessing 163 BILLSTATUS files from the 114th Congress that were not updated with the original reprocess.
