### ISSUE TITLE
Large quantity of 114th Congress bills updated 10/21 or 10/22

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#27]
5882  house bills were updated according to the sitemap:

https://www.gpo.gov/smap/bulkdata/BILLSTATUS/114hr/sitemap.xml

Is it possible to get some details about what information was updated for all of these bills.

**Comment by 104PL104** [comment]
During "scheduled non-legislative periods" (times like now when neither House nor Senate are actively conducting legislative business) normal behavior that you should expect is that update dates will change, although the content isn't actually changing. It is due to maintenance of data systems that is performed during Congressional downtime.

We have an objective to eventually prevent maintenance-induced update date changes, but for now expect such as normal behavior.

**Comment by llaplant** [comment]
Deployment on November 3rd. We will reprocess data after the deployment. Update dates will change for reprocessed data.

**Comment by llaplant** [comment]
We are currently processing existing and new 114th bill status files to make sure new fields are available for the entire data set. Data will continue to be updated throughout the day and night. Estimated time to complete is 2 days.

**Comment by JoshData** [comment]
So regular updates, including activity from Monday forward, might not make it into the data until the end of the week?

**Comment by llaplant** [comment]
During our current development sprint, we are looking at how to run the regular bill status job in parallel with bill status reprocessing. We are also looking at ways to update the priority of bill status files in the processing queue. This currently requires manual intervention. Files are added to the processing queue as part of the regular bill status job and also as part of bill status reprocessing. The following are now available. 

BILLSTATUS-114hr6241
BILLSTATUS-114hr6242
BILLSTATUS-114hr6244
BILLSTATUS-114hr6245
BILLSTATUS-114hr6246
BILLSTATUS-114hr6247
BILLSTATUS-114hr6248
BILLSTATUS-114hr6249
BILLSTATUS-114hr6250
BILLSTATUS-114hr6251
BILLSTATUS-114hr6252
BILLSTATUS-114hr6253
BILLSTATUS-114hr6254
BILLSTATUS-114hr6255
BILLSTATUS-114hr6256
BILLSTATUS-114hr6257
BILLSTATUS-114hr6258
BILLSTATUS-114hr6260
BILLSTATUS-114hr6261
BILLSTATUS-114hr6262
BILLSTATUS-114hr6263
BILLSTATUS-114hr6264
BILLSTATUS-114hr6265
BILLSTATUS-114hr6266
BILLSTATUS-114hr6267
BILLSTATUS-114hr6268
BILLSTATUS-114hr6269
BILLSTATUS-114hr6270
BILLSTATUS-114hr6273
BILLSTATUS-114hr6274
BILLSTATUS-114hr6275
BILLSTATUS-114hr6276
BILLSTATUS-114hr6277
BILLSTATUS-114hr6278
BILLSTATUS-114hr6279
BILLSTATUS-114hr6280
BILLSTATUS-114hr6281
BILLSTATUS-114hr6283
BILLSTATUS-114hr6284
BILLSTATUS-114hr6285
BILLSTATUS-114hr6286
BILLSTATUS-114hr6287
BILLSTATUS-114hr6288
BILLSTATUS-114hr6289
BILLSTATUS-114hr6290
BILLSTATUS-114hr6291
BILLSTATUS-114hr6292
BILLSTATUS-114hr6293
BILLSTATUS-114hr6294
BILLSTATUS-114hr6295
BILLSTATUS-114hr6297
BILLSTATUS-114hr6298
BILLSTATUS-114hr6299
BILLSTATUS-114hr6300
BILLSTATUS-114hr6301
BILLSTATUS-114hr6302
BILLSTATUS-114hr6303
BILLSTATUS-114hr6304
BILLSTATUS-114hr6305
BILLSTATUS-114hr6306
BILLSTATUS-114hr6307
BILLSTATUS-114hr6308
BILLSTATUS-114hr6309
BILLSTATUS-114hr6310
BILLSTATUS-114hr6311
BILLSTATUS-114hr6312
BILLSTATUS-114hr6313
BILLSTATUS-114hr6314
BILLSTATUS-114hr6315
BILLSTATUS-114hr6316
BILLSTATUS-114hr6317
BILLSTATUS-114hr6318
BILLSTATUS-114hr6319
BILLSTATUS-114hr6320
BILLSTATUS-114hr6321
BILLSTATUS-114hr6322
BILLSTATUS-114hr6323

**Comment by JoshData** [comment]
Thanks. 

On November 16, 2016 3:41:11 PM EST, Lisa LaPlant <notifications@github.com> wrote:
>During our current development sprint, we are looking at how to run the
>regular bill status job in parallel with bill status reprocessing. We
>are also looking at ways to update the priority of bill status files in
>the processing queue. This currently requires manual intervention.
>Files are added to the processing queue as part of the regular bill
>status job and also as part of bill status reprocessing. The following
>are now available. 
>
>BILLSTATUS-114hr6241
>BILLSTATUS-114hr6242
>BILLSTATUS-114hr6244
>BILLSTATUS-114hr6245
>BILLSTATUS-114hr6246
>BILLSTATUS-114hr6247
>BILLSTATUS-114hr6248
>BILLSTATUS-114hr6249
>BILLSTATUS-114hr6250
>BILLSTATUS-114hr6251
>BILLSTATUS-114hr6252
>BILLSTATUS-114hr6253
>BILLSTATUS-114hr6254
>BILLSTATUS-114hr6255
>BILLSTATUS-114hr6256
>BILLSTATUS-114hr6257
>BILLSTATUS-114hr6258
>BILLSTATUS-114hr6260
>BILLSTATUS-114hr6261
>BILLSTATUS-114hr6262
>BILLSTATUS-114hr6263
>BILLSTATUS-114hr6264
>BILLSTATUS-114hr6265
>BILLSTATUS-114hr6266
>BILLSTATUS-114hr6267
>BILLSTATUS-114hr6268
>BILLSTATUS-114hr6269
>BILLSTATUS-114hr6270
>BILLSTATUS-114hr6273
>BILLSTATUS-114hr6274
>BILLSTATUS-114hr6275
>BILLSTATUS-114hr6276
>BILLSTATUS-114hr6277
>BILLSTATUS-114hr6278
>BILLSTATUS-114hr6279
>BILLSTATUS-114hr6280
>BILLSTATUS-114hr6281
>BILLSTATUS-114hr6283
>BILLSTATUS-114hr6284
>BILLSTATUS-114hr6285
>BILLSTATUS-114hr6286
>BILLSTATUS-114hr6287
>BILLSTATUS-114hr6288
>BILLSTATUS-114hr6289
>BILLSTATUS-114hr6290
>BILLSTATUS-114hr6291
>BILLSTATUS-114hr6292
>BILLSTATUS-114hr6293
>BILLSTATUS-114hr6294
>BILLSTATUS-114hr6295
>BILLSTATUS-114hr6297
>BILLSTATUS-114hr6298
>BILLSTATUS-114hr6299
>BILLSTATUS-114hr6300
>BILLSTATUS-114hr6301
>BILLSTATUS-114hr6302
>BILLSTATUS-114hr6303
>BILLSTATUS-114hr6304
>BILLSTATUS-114hr6305
>BILLSTATUS-114hr6306
>BILLSTATUS-114hr6307
>BILLSTATUS-114hr6308
>BILLSTATUS-114hr6309
>BILLSTATUS-114hr6310
>BILLSTATUS-114hr6311
>BILLSTATUS-114hr6312
>BILLSTATUS-114hr6313
>BILLSTATUS-114hr6314
>BILLSTATUS-114hr6315
>BILLSTATUS-114hr6316
>BILLSTATUS-114hr6317
>BILLSTATUS-114hr6318
>BILLSTATUS-114hr6319
>BILLSTATUS-114hr6320
>BILLSTATUS-114hr6321
>BILLSTATUS-114hr6322
>BILLSTATUS-114hr6323
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/usgpo/bill-status/issues/27#issuecomment-261065266

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
