### ISSUE TITLE
bills on congress.gov not on fdsys

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#28]
As of right now, the highwater mark for house bills on FDSYS is BILLSTATUS-114hr6323.xml and the latest introduced bill on congress.gov is  H.R.6335 

I presume this is caused by the reprocessing, but can you provide a sense of when these bills will be available as FDSYS xml.

**Comment by llaplant** [comment]
High water mark for House bills is now BILLSTATUS-114hr6335.xml. Reprocessing should finish over night.

**Comment by wcarter** [comment]
Thank you
