### ISSUE TITLE
cosponsor not current in fdsys bill status xml

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#29]
For example, congress.gov has claire mccaskill as a cosponsor of s375 as of 11/16/2016

https://www.congress.gov/bill/114th-congress/senate-bill/375/cosponsors?

but she is not included in the xml which is:  <lastmod>2016-11-17T04:04:01.514Z</lastmod>

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s375.xml

**Comment by llaplant** [comment]
This file was updated again around 11:15 this morning and is available now. New updates are continuing to flow through.

**Comment by wcarter** [comment]
Thanks.  Must have been going through as I was writing about it.  I see the highwater mark for house bills is still BILLSTATUS-114hr6335.xml  and congress.gov is hr6379.  Do you expect those new introduced bills to flow through soon?

**Comment by llaplant** [comment]
Yes

**Comment by llaplant** [comment]
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s375.xml
