### ISSUE TITLE
Amendment XML elements don't contain bioguide ids

### ISSUE THREAD

**Issue by dwillis** [usgpo/bill-status#3]
Amendment XML elements are missing the bioguide ID from the amendment sponsor (where there is one). For example: https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr1314.xml 

Can bioguide IDs be added?

**Comment by llaplant** [comment]
@dwillis check out the sample file at https://github.com/usgpo/bill-status/blob/master/BILLSTATUS-114hr1314.xml. This is in the works for our April release.

**Comment by dwillis** [comment]
Excellent, thank you.
