### ISSUE TITLE
S.Res. 578 is missing a title

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#30]
S.Res. 578 doesn't have a title.

This is the case both in the data and on Congress.gov, which also indicates GPO hasn't published text for the resolution yet (it was introduced two months ago).

https://www.congress.gov/bill/114th-congress/senate-resolution/578
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/sres/BILLSTATUS-114sres578.xml

**Comment by llaplant** [comment]
S. Res. 578 (IS) was ingested into FDsys/govinfo on 9/27/2016 per the ingest date in MODS.
https://www.gpo.gov/fdsys/pkg/BILLS-114sres578is/html/BILLS-114sres578is.htm
https://www.gpo.gov/fdsys/pkg/BILLS-114sres578is/pdf/BILLS-114sres578is.pdf
https://www.gpo.gov/fdsys/pkg/BILLS-114sres578is/xml/BILLS-114sres578is.xml
https://www.gpo.gov/fdsys/pkg/BILLS-114sres578is/mods.xml
https://www.gpo.gov/fdsys/pkg/BILLS-114sres578is/premis.xml
https://www.gpo.gov/fdsys/bulkdata/BILLS/114/2/sres/BILLS-114sres578is.xml

S. Res. 578 (ATS) was ingested into FDsys/govinfo on 10/01/2016 per the ingest date in MODS.
https://www.gpo.gov/fdsys/pkg/BILLS-114sres578ats/html/BILLS-114sres578ats.htm
https://www.gpo.gov/fdsys/pkg/BILLS-114sres578ats/pdf/BILLS-114sres578ats.pdf
https://www.gpo.gov/fdsys/pkg/BILLS-114sres578ats/xml/BILLS-114sres578ats.xml
https://www.gpo.gov/fdsys/pkg/BILLS-114sres578ats/mods.xml
https://www.gpo.gov/fdsys/pkg/BILLS-114sres578ats/premis.xml
https://www.gpo.gov/fdsys/bulkdata/BILLS/114/2/sres/BILLS-114sres578ats.xml

Sitemap entries are available for IS and ATS.
https://www.gpo.gov/smap/fdsys/sitemap_2016/2016_BILLS_sitemap.xml
2016-09-28T00:02:00.275Z
2016-10-01T04:08:01.535Z
https://www.gpo.gov/smap/bulkdata/BILLS/114sres/sitemap.xml
2016-09-28T00:02:00.558Z
2016-10-01T04:08:04.542Z

**Comment by llaplant** [comment]
https://www.congress.gov/bill/114th-congress/senate-resolution/578/titles
