### ISSUE TITLE
TEST title in billStatus for HR 5148

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#31]
HR 5148 has a TEST display title and  the parentTitleType and titleType values for official titles don't match the rest of the bill status corpus.      I assume this is a data error?

  <bill>
    <title>TEST</title>
    <updateDate>2016-11-02T22:43:49Z</updateDate>

and:

   <titles>
      <item>
        <chamberCode />
        <chamberName />
        <title>To amend the Department of Education Organization Act and the Higher Education Act of 1965 to require publication of information relating to religious exemptions to the requirements of title IX of the Education Amendments of 1972, and for other purposes.</title>
        <parentTitleType>Short Title</parentTitleType>
        <titleType>Other Short Titles</titleType>
      </item>
      <item>
        <chamberCode />
        <chamberName />
        <title>Transparency in Taypayer-Funded [sic] Discrimination Act</title>
        <parentTitleType />
        <titleType>Short Titles as Introduced</titleType>
      </item>
      <item>
        <chamberCode />
        <chamberName />
        <title>TEST</title>
        <parentTitleType />
        <titleType>Override Display Title</titleType>
      </item>
      <item>
        <chamberCode />
        <chamberName />
        <title>To amend the Department of Education Organization Act and the Higher Education Act of 1965 to require publication of information relating to religious exemptions to the requirements of title IX of the Education Amendments of 1972, and for other purposes.</title>
        <parentTitleType>Official Title</parentTitleType>
        <titleType>Official Titles on Other Bill Versions</titleType>
      </item>
      <item>
        <chamberCode />
        <chamberName />
        <title>To amend the Department of Education Organization Act and the Higher Education Act of 1965 to require publication of information relating to religious exemptions to the requirements of title IX of the Education Amendments of 1972, and for other purposes.</title>
        <parentTitleType />
        <titleType>Official Title as Introduced</titleType>
      </item>
      <item>
        <chamberCode />
        <chamberName />
        <title>TEST</title>
        <parentTitleType />
        <titleType>Display Title</titleType>
      </item>
    </titles>

**Comment by 104PL104** [comment]
Thank you for reporting that. Yes. Error. We'll get that corrected.

**Comment by llaplant** [comment]
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr5148.xml
