### ISSUE TITLE
duplicate actions display on congress.gov

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#32]
I understand that duplicate actions are present in the BillStatus xml.  However, there are a couple of bills that have duplicate actions that are displaying on congress.gov and looks like it might be some kind of data anomaly:

For example HR 5937

Date	Chamber	All Actions
09/29/2016		Became Public Law No: 114-227. 
09/29/2016		Became Public Law No: 114-227. 
09/29/2016		Signed by President. 
09/29/2016		Signed by President. 
09/26/2016	House	Presented to President. 
09/26/2016	House	Presented to President. 

Also:  HR 4721

**Comment by llaplant** [comment]
https://www.congress.gov/bill/114th-congress/house-bill/5937/actions and https://www.congress.gov/bill/114th-congress/house-bill/4721/actions
