### ISSUE TITLE
S RES 578 has very little metadata -- no title or text on congress.gov 

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#33]
There are bill text versions on fdsys.  Here's the text of the ats version:

https://www.gpo.gov/fdsys/pkg/BILLS-114sres578ats/html/BILLS-114sres578ats.htm

**Comment by 104PL104** [comment]
Thank you for reporting this, also. We'll reprocess this and get the complete record out.

**Comment by llaplant** [comment]
https://www.congress.gov/bill/114th-congress/senate-resolution/578/text and https://www.congress.gov/bill/114th-congress/senate-resolution/578/titles
