### ISSUE TITLE
Senate Amendment Cosponsors missing in Bill-Status xml

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#34]
for example, S 2848 Amendment 4997:

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s2848.xml

on congress.gov  Jeff Flake is cosponsor:

https://www.congress.gov/amendment/114th-congress/senate-amendment/4997/cosponsors

In Bill Status I see cosponsor count, but not information on who that cosponsor is:

<amendment>
<number>4997</number>
<description/>
<congress>114</congress>
<purpose/>
<type>SAMDT</type>
<latestAction/>
<purpose/>
<congress>114</congress>
<updateDate>2016-12-01T19:31:22Z</updateDate>
<titles/>
<links/>
<cosponsors>
<currentCount>1</currentCount>
<totalCount>1</totalCount>
</cosponsors>
<sponsors>
<item>
<bioguideId>M000303</bioguideId>
<firstName>JOHN</firstName>
<lastName>MCCAIN</lastName>
<party>R</party>
<state>AZ</state>
<middleName>SIDNEY</middleName>
<fullName>Sen. McCain, John [R-AZ]</fullName>
</item>
</sponsors>
<notes/>
<amendedBill>
<congress>114</congress>
<title>Water Resources Development Act of 2016</title>
<number>2848</number>
<originChamberCode>S</originChamberCode>
<originChamber>Senate</originChamber>
<type>S</type>
</amendedBill>
<description/>
<chamber>Senate</chamber>
<actions>
<count>2</count>
<actions>
<item>
<actionDate>2016-09-08</actionDate>
<committee/>
<links/>
<text/>
</item>
<item>
<actionDate>2016-09-08</actionDate>
<actionCode>91000</actionCode>
<committee/>
<links/>
<type>Floor</type>
<sourceSystem>
<code>9</code>
<name>Library of Congress</name>
</sourceSystem>
<text>Senate amendment submitted</text>
</item>
</actions>
<actionByCounts>
<senate>1</senate>
</actionByCounts>
<actionTypeCounts>
<senateAmendmentSubmitted>1</senateAmendmentSubmitted>
</actionTypeCounts>
</actions>
<number>4997</number>
<amendments>
<count>0</count>
</amendments>
<submittedDate>2016-09-08T04:00:00Z</submittedDate>
<type>SAMDT</type>
<proposedDate/>
<amendedAmendment>
<description/>
<purpose>In the nature of a substitute.</purpose>
<congress>114</congress>
<number>4979</number>
<type>SAMDT</type>
</amendedAmendment>
<createDate>2016-09-09T09:03:31Z</createDate>
</amendment>

**Comment by llaplant** [comment]
A sample file from our dev integration environment is available at https://github.com/usgpo/bill-status/blob/master/BILLSTATUS-114s2848.xml. @wcarter let me know if this works for you. Our next Production release is scheduled for the last week in March.

**Comment by wcarter** [comment]
Looks good.  Thanks @llaplant

**Comment by llaplant** [comment]
I'll let you know when the fix is deployed and the file is reprocessed.

**Comment by llaplant** [comment]
Resolved
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s2848.xml
