### ISSUE TITLE
Bill was both signed by the president and not signed by the president

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#35]
H.R. 6297 has conflicting information.

	<item>
	  <text>Sent to Archivist of the United States unsigned.</text>
	  <actionCode>E30000</actionCode>
	  <type>President</type>
	  <sourceSystem>
	    <code>2</code>
	    <name>House floor actions</name>
	  </sourceSystem>
	  <actionDate>2016-12-15</actionDate>
	</item>
	<item>
	  <text>Signed by President.</text>
	  <actionCode>E30000</actionCode>
	  <type>President</type>
	  <sourceSystem>
	    <code>9</code>
	    <name>Library of Congress</name>
	  </sourceSystem>
	  <actionDate>2016-12-15</actionDate>
	</item>

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr6297.xml

Both can't be true.

Congress.gov only lists "Sent to Archivist of the United States unsigned.".

https://www.congress.gov/bill/114th-congress/house-bill/6297/all-actions

This is a pretty serious data error, with constitutional ramifications.

**Comment by llaplant** [comment]
LOC data updated and billstatus reprocessed from LOC data.

**Comment by JoshData** [comment]
Thank you that was so fast! :)
