### ISSUE TITLE
115th House bills available on congress.gov but not fdsys

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#36]
The sitemap has no entry for 115hr, though I see congress.gov is up to HR 237 for the new congress.

https://www.gpo.gov/smap/bulkdata/BILLSTATUS/sitemapindex.xml

Will these bills be in the 4:00 pm update?

**Comment by llaplant** [comment]
Happy New Year! 
We are making BILLSTATUS data available as it becomes available to GPO via the LOC feed and as it can be successfully processed in FDsys. Some of the H.R. BILLSTATUS files are now available for the 115th Congress. One item of note-- the 114th Congress job is continuing to run at 4, 8, and 12. We are temporarily running the 115th Congress job at 6, 10, and 2. After the volume of updates for the 114th Congress decreases, we are planning to switch the 115th Congress job to 4, 8, and 12.
