### ISSUE TITLE
cbo cost estimate items duplicated in bill status xml

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#37]
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/113/hr/BILLSTATUS-113hr1.xml

<cboCostEstimates>
<item>
<title>H.R. 1, Disaster Relief Appropriations Act, 2013</title>
<pubDate>2013-01-17T18:44:00Z</pubDate>
<url>http://www.cbo.gov/publication/43853</url>
</item>
<item>
<title>H.R. 1, Disaster Relief Appropriations Act, 2013</title>
<pubDate>2013-01-17T18:44:00Z</pubDate>
<url>https://www.cbo.gov/publication/43853</url>
</item>
</cboCostEstimates>

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/113/hr/BILLSTATUS-113hr2871.xml

<cboCostEstimates>
<item>
<title>
H.R. 2871, a Bill to Amend Title 28, United States Code, to Modify the Composition of the Southern Judicial District of Mississippi to Improve Judicial Efficiency, and for Other Purposes
</title>
<pubDate>2013-09-24T21:49:21Z</pubDate>
<url>http://www.cbo.gov/publication/44615</url>
</item>
<item>
<title>
H.R. 2871, a Bill to Amend Title 28, United States Code, to Modify the Composition of the Southern Judicial District of Mississippi to Improve Judicial Efficiency, and for Other Purposes
</title>
<pubDate>2013-09-24T21:49:21Z</pubDate>
<url>https://www.cbo.gov/publication/44615</url>
</item>
</cboCostEstimates>

**Comment by 104PL104** [comment]
This has been corrected in the source data. Expect to see it in the bulk data soon.
