### ISSUE TITLE
sponsor information is  being dropped from 114th bills on congress.gov/fdsys xml 

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#38]
For example:

https://www.congress.gov/bill/114th-congress/senate-bill/3205

Sponsor:	No Sponsor (Introduced 07/13/2016)

We have found about 20 bills with this condition thus far.

**Comment by 104PL104** [comment]
Thank you for reporting this.

**Comment by llaplant** [comment]
Sponsor:	Sen. Lee, Mike [R-UT] (Introduced 07/13/2016)
https://www.congress.gov/bill/114th-congress/senate-bill/3205

Are there others that are missing sponsor information?

**Comment by JoshData** [comment]
s1024, s1177, s125, s1318, s1479, s1607, s2348, s2399, s2624, s2700, s2781, s2876, s2947, s2949, s2950, s2951, s2961, s2963, s2971, s2993, s2997, s3317, s483

**Comment by 104PL104** [comment]
These have been corrected and reprocessed. Confirming that the data flowed through correctly prior to closing the ticket.

**Comment by JoshData** [comment]
Looks like there are 36 bills in the 115th Congress now showing the same problem.

**Comment by JoshData** [comment]
90 bills in the 114th are missing sponsor info now.

**Comment by JoshData** [comment]
We're down to 2 bills in the 114th that are missing sponsor info:

https://www.gpo.gov//fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s3181.xml
https://www.gpo.gov//fdsys/bulkdata/BILLSTATUS/114/s/BILLSTATUS-114s3476.xml

**Comment by llaplant** [comment]
Reprocessed the two files above. Please check.

**Comment by JoshData** [comment]
Thanks, all good! (This is the first time since the 115th Congress began that I've been able to do a complete parse of the 114th Congress.)

**Comment by JoshData** [comment]
There are (suddenly) 28 bills in the 115th Congress with this same problem. It's also missing on Congress.gov:

https://www.congress.gov/bill/115th-congress/senate-bill/135
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s135.xml

**Comment by llaplant** [comment]
Checked links above. If issue reappears, please let me know and I will reopen.
