### ISSUE TITLE
Garbled action 

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#39]
https://www.congress.gov/amendment/114th-congress/house-amendment/752/actions

11/03/2015	Amendment reported by the House Committee on Welch to the Rules amendment (A001). (consideration: CR H7593-7594; text: CR H7593)

**Comment by 104PL104** [comment]
The action appears to be OK, correct? If not, please specify the issue.

**Comment by 104PL104** [comment]
This has been corrected in the source data. Expect to see it in the bulk data soon.
