### ISSUE TITLE
Missing forward slash in vote URL

### ISSUE THREAD

**Issue by GullicksonK** [usgpo/bill-status#4]
The URLs for the vote XML on the Clerk’s website is missing the forward slash between “EVS” and the year.

Incorrect:  <url>http://clerk.house.gov/evs2016/roll020.xml</url>
Correct: <url>http://clerk.house.gov/evs/2016/roll020.xml</url>

**Comment by llaplant** [comment]
Fixed and reprocessed! 
For example, see https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr1155.xml for the URL for Roll Call 20.
