### ISSUE TITLE
Floor action identified as President

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#41]
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hres/BILLSTATUS-114hres450.xml

I don't  believe this is a type=President action.

<item>
<type>President</type>
<text>
On motion to discharge Agreed to by the Yeas and Nays: 246 - 177 (Roll no. 569). (consideration: CR H7182)
</text>
<actionCode>H30841</actionCode>
<sourceSystem>
<name>House floor actions</name>
<code>2</code>
</sourceSystem>
<links>
<link>
<url>
https://www.congress.gov/congressional-record/volume-161/house-section/page/H7182
</url>
<name>H7182</name>
</link>
<link>
<url>http://clerk.house.gov/evs/2015/roll569.xml</url>
<name>Roll no. 569</name>
</link>
</links>
<committee/>
<actionDate>2015-10-26</actionDate>
</item>

**Comment by llaplant** [comment]
Checking source data.

**Comment by llaplant** [comment]
Please let me know if still an issue and I will reopen. 

https://www.congress.gov/bill/114th-congress/house-resolution/450/all-actions

https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hres/BILLSTATUS-114hres450.xml
