### ISSUE TITLE
S. 247 has 15 co-sponsors, with "no-cosponsors" listed

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#42]
Hi, I'm having a problem with co-sponsors for S. 247: https://www.congress.gov/bill/115th-congress/senate-bill/247/cosponsors.

Under the co-sponsors tab, it says there are 15 co-sponsors but there are none listed and I see the message "No cosponsors."

**Comment by 104PL104** [comment]
Thank you for reporting this. We are making a correction in the source data, and will reprocess.

**Comment by 104PL104** [comment]
Data has been reprocessed and is now correct in source
