### ISSUE TITLE
Truncated action

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#43]
https://www.congress.gov/bill/114th-congress/house-resolution/255/all-actions

05/12/2015-10:25pm	Providing for consideration of H.R. 1735, H.R. 36, and 

Presumably there should be another bill number after "and"?

**Comment by 104PL104** [comment]
Thank you for reporting this. We'll check with the data owner.

**Comment by 104PL104** [comment]
This has been corrected at the source. Expect is to flow through soon. Thanks.
