### ISSUE TITLE
house amendment given senate sponsor in bill-status xml

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#44]
115 SCONRES 3 coincidentally has both SAMDT 44 and HAMDT 44 as amendments.  

In the FDSYS xml most of the metadata for the HAMDT actually belongs to SAMDT 44.

it looks okay on congress.gov: https://www.congress.gov/amendment/115th-congress/house-amendment/44?

FROM:

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/sconres/BILLSTATUS-115sconres3.xml

<amendment>
<description>
Strike all after the resolving clause and insert the following: SECTION 1. CONCURRENT RESOLUTION ON THE BUDGET FOR FISCAL YEAR 2017. (a) Declaration- Congress declares that this resolution is the concurrent resolution on the budget for fiscal year 2017 and that this resolution sets forth the appropriate budgetary levels for fiscal years 2018 through 2026. ***.
</description>
<congress>115</congress>
<number>44</number>
<type>HAMDT</type>
<latestAction>
<actionDate>2017-01-13</actionDate>
<actionTime>15:25:57</actionTime>
<text>
On agreeing to the Yarmuth amendment (A001) Failed by recorded vote: 149 - 272 (Roll no. 57).
</text>
</latestAction>
<purpose>Amendment in the nature of a substitute.</purpose>
<number>44</number>
<description/>
<purpose/>
<type>SAMDT</type>
<createDate>2017-01-10T10:17:07Z</createDate>
<updateDate>2017-02-04T10:13:35Z</updateDate>
<cosponsors>
<currentCount>0</currentCount>
<totalCount>0</totalCount>
</cosponsors>
<submittedDate>2017-01-09T05:00:00Z</submittedDate>
<notes/>
<sponsors>
<item>
<fullName>Sen. Flake, Jeff [R-AZ]</fullName>
<firstName>JEFF</firstName>
<state>AZ</state>
<party>R</party>
<lastName>FLAKE</lastName>
<middleName/>
<bioguideId>F000444</bioguideId>
</item>
</sponsors>
<amendedBill>
<congress>115</congress>
<originChamberCode>S</originChamberCode>
<title>
A concurrent resolution setting forth the congressional budget for the United States Government for fiscal year 2017 and setting forth the appropriate budgetary levels for fiscal years 2018 through 2026.
</title>
<type>SCONRES</type>
<number>3</number>
<originChamber>Senate</originChamber>
</amendedBill>
<links/>
<congress>115</congress>
<proposedDate/>
<actions>
<count>2</count>
<actions>
<item>
<actionDate>2017-01-09</actionDate>
<committee/>
<links/>
<text/>
</item>
<item>
<text>Senate amendment submitted</text>
<actionDate>2017-01-09</actionDate>
<sourceSystem>
<name>Library of Congress</name>
<code>9</code>
</sourceSystem>
<committee/>
<type>Floor</type>
<links/>
<actionCode>91000</actionCode>
</item>
</actions>
<actionTypeCounts>
<senateAmendmentSubmitted>1</senateAmendmentSubmitted>
</actionTypeCounts>
<actionByCounts>
<senate>1</senate>
</actionByCounts>
</actions>
<amendedAmendment/>
<chamber>Senate</chamber>
<amendments>
<count>0</count>
</amendments>
<titles/>
</amendment>

**Comment by llaplant** [comment]
A sample file from our dev integration environment is available at https://github.com/usgpo/bill-status/blob/master/BILLSTATUS-115sconres3.xml. @wcarter let me know if this works for you. Our next Production release is scheduled for the last week in March.

**Comment by wcarter** [comment]
sample file looks good.

**Comment by llaplant** [comment]
Great! I'll let you know when the fix is deployed and the file is reprocessed.

**Comment by llaplant** [comment]
ttps://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/sconres/BILLSTATUS-115sconres3.xml
