### ISSUE TITLE
To Include Bill Version in Bill Status Document

### ISSUE THREAD

**Issue by ghost** [usgpo/bill-status#45]
Legislation may be changed or amended as it makes its way through the legislative process. You will sometimes see different bill text versions in the Text tab of a bill record. A list of the different versions are in the [link](https://www.gpo.gov/help/about_congressional_bills.htm).

Versions are needed for accessing bills the following xml pages:
[Bill Summary (In URL)](https://www.gpo.gov/fdsys/pkg/BILLS-115hconres1eh/html/BILLS-115hconres1eh.htm)
[CONGRESSIONAL BILLS - BULK DATA](https://www.gpo.gov/fdsys/bulkdata/BILLS/115/1/hr)

**Comment by llaplant** [comment]
Thank you for the suggestion.

**Comment by aosingh** [comment]
Hi @llaplant 

Are there any updates on this enhancement ?

Thank you.
Abhishek

**Comment by llaplant** [comment]
It is on the backlog but not scheduled yet. Would a service that provides a json or xml list of available bill versions be helpful?

**Comment by dwillis** [comment]
Yes, particularly if it indicated the order (most recent version first, for example).

**Comment by dwillis** [comment]
@llaplant is there any update on this?

**Comment by llaplant** [comment]
@dwillis not yet, but check back mid-July after the LDTC18 conference. @jonquandt

**Comment by dwillis** [comment]
@llaplant @jonquandt Any update on this?

**Comment by jonquandt** [comment]
@dwillis -- we recently launched our [API](https://api.govinfo.gov/docs). We do have a planned feature for listing all available bill versions based on a BILLSTATUS packageid or Congress number and bill number.

See https://github.com/usgpo/api/issues/3

Any feedback or input you have on that would be great as we start looking at developing it. 

Currently, all BILLS package summaries returned by the API include a link to the related BILLSTATUS package.

https://api.govinfo.gov/packages/BILLS-115hconres1eh/summary?api_key=DEMO_KEY


>"related": {
"billStatusLink": "https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hconres/BILLSTATUS-115hconres1.xml"
},

**Comment by dwillis** [comment]
Thanks, @jonquandt - what about in the bulk data?

**Comment by jonquandt** [comment]
@dwillis - we're looking at the options for this one, and I'll let you know when we'll have something more firm to share, including deployment timeframe.

**Comment by llaplant** [comment]
Proposed addition of `<textVersions>`.
Check out the sample files and let us know what you think. 
- [DEV-BILLSTATUS-115hr302.xml](DEV-BILLSTATUS-115hr302.xml)
- [DEV-BILLSTATUS-115hr367.xml](DEV-BILLSTATUS-115hr367.xml)
- [DEV-BILLSTATUS-115s2269.xml](DEV-BILLSTATUS-115s2269.xml)
- [DEV-BILLSTATUS-115s3509.xml](DEV-BILLSTATUS-115s3509.xml)

**Comment by dwillis** [comment]
@llaplant Thanks! I think those are really great and would support their inclusion.

**Comment by llaplant** [comment]
Enabling for 116th Congress and reprocessing existing files 116 BILLSTATUS XML.

**Comment by llaplant** [comment]
116 and 115 should be good. Will appear in 114 and 113 next time files are reprocessed. 
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr123.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr123.xml

**Comment by dwillis** [comment]
Thanks!!
