### ISSUE TITLE
Why does "all actions" display on congress.gov vary

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#46]
Question more than issue, but I am very curious about the answer.

Sometimes there are 3 columns -- date, chamber and all actions --  and an  "Action By: X" string is added on a new line for committee actions:

https://www.congress.gov/bill/115th-congress/house-bill/1004/all-actions?

Sometimes there are 2 columns --  date and all actions --  and  every action has an "Action By: X" string  that specifies chamber, except for committee actions

https://www.congress.gov/bill/115th-congress/house-bill/1215/all-actions?

These are both house bills from the current congress

**Comment by 104PL104** [comment]
The "Chamber" column is only present if more than one chamber has acted on the measure.

HR1215 was introduced in the House, and is pending in the House. 

HR1004 passed the House, and has been referred to a Senate committee which triggers the "Chamber" column to be present.

**Comment by wcarter** [comment]
Thanks!  I figured it was a rule like that, but I thought I had seen some examples that did not conform to it and wanted to check.
