### ISSUE TITLE
Missing Amendments on Amendment Tab for H.R. 985, H.R. 725

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#47]
Hoping this is the right spot to submit this issue--on the amendment tab for H.R. 985 and H.R. 725 it shows the amendments to the bill that were considered, but when I click the "Amendments" tab none are listed.

H.R. 985 (8 amendments): https://www.congress.gov/bill/115th-congress/house-bill/985/amendments?r=1
H.R. 725 (2 amendments): https://www.congress.gov/bill/115th-congress/house-bill/725/amendments?q=%7B%22search%22%3A%5B%22hr725%22%5D%7D&r=1

Both bills have the amendments listed and linked with roll call votes under the "Actions" tab on their bill pages.

**Comment by 104PL104** [comment]
Thank you for reporting this. There was a processing disruption for House amendments 66-75 that were introduced yesterday.

I believe all has been resolved. Please check again. Sorry for the inconvenience.

**Comment by llaplant** [comment]
Verified amendments are available on the Congress.gov Amendments tab.
