### ISSUE TITLE
Bulk data for HR 131 (114th Congress) contains duplicate co-sponsors

### ISSUE THREAD

**Issue by hhubik** [usgpo/bill-status#48]
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr131.xml contains duplicate co-sponsors.

For example, Rep. Hanna, Richard L. [R-NY-22] is listed twice, but there are at least 8 or 9 other duplicates.

**Comment by llaplant** [comment]
Resolved
