### ISSUE TITLE
Missing bill: HJRes 86

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#49]
This bill is on Congress.gov:

https://www.congress.gov/bill/115th-congress/house-joint-resolution/86

But not in the bulk data:

https://www.gpo.gov//fdsys/bulkdata/BILLSTATUS/115/hjres/

**Comment by llaplant** [comment]
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/hjres/BILLSTATUS-115hjres86.xml

**Comment by JoshData** [comment]
That wasn't there a moment ago! :)

**Comment by llaplant** [comment]
It's magic ;)
