### ISSUE TITLE
Co-sponsor issues for a few bills

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#50]
Hello, for a few of the senate bills there are issues on the co-sponsors tab. Each of them list how many senators have co-sponsored the bill, but when I go to view that tab it says "no cosponsors".

S. 652: https://www.congress.gov/bill/115th-congress/senate-bill/652/cosponsors?q=%7B%22search%22%3A%5B%22s652%22%5D%7D&r=1
S. 623: https://www.congress.gov/bill/115th-congress/senate-bill/623/cosponsors?q=%7B%22search%22%3A%5B%22s623%22%5D%7D&r=1
S. 573: https://www.congress.gov/bill/115th-congress/senate-bill/573/cosponsors?q=%7B%22search%22%3A%5B%22s573%22%5D%7D&r=1
S. 540: https://www.congress.gov/bill/115th-congress/senate-bill/540/cosponsors?q=%7B%22search%22%3A%5B%22s540%22%5D%7D&r=1
S. 544: https://www.congress.gov/bill/115th-congress/senate-bill/544/cosponsors?q=%7B%22search%22%3A%5B%22s544%22%5D%7D&r=1

**Comment by 104PL104** [comment]
Thank you for reporting this. We are working on a fix.

**Comment by llaplant** [comment]
Cosponsors are listed for bills referenced above.
