### ISSUE TITLE
Some 114th Congress cosponsorships has incorrect fullName, missing district

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#51]
In a handful of bills from the 114th Congress, like [H.Res. 12](https://www.gpo.gov//fdsys/bulkdata/BILLSTATUS/114/hres/BILLSTATUS-114hres12.xml), cosponsor/fullName has "None" in place of a district number.

    <fullName>Rep. Duckworth, Tammy [D-IL-None]</fullName>

hr158-114, hr174-114, hres12-114: `Rep. Duckworth, Tammy [D-IL-None]`

hr24-114, hr30-114, hr36-114, hr160-114, hr169-114: `Rep. Young, Todd C. [R-IN-None]`

hr91-114, hr154-114: `Rep. Van Hollen, Chris [D-MD-None]`

**Comment by 104PL104** [comment]
Thank you for reporting this. We are working on a fix.

**Comment by llaplant** [comment]
Checked on Prod. Looks good!

Duckworth
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hres/BILLSTATUS-114hres12.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr158.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr174.xml

Young
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr24.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr30.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr36.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr160.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr169.xml

Van Hollen
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr91.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr154.xml
