### ISSUE TITLE
Bills Missing Sponsor, Title

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#52]
Hello, there are several bills that were introduced yesterday with zero title or sponsor information in the bill status files. Would you please investigate this issue? Thank you!

S.801
S.804
S.RES.108
S.802
S.803
S.805	
S.806
H.R.1849
H.R.1848

**Comment by 104PL104** [comment]
Thank you for reporting this. We're tending to it now.

**Comment by llaplant** [comment]
Resolved at LOC and files reprocessed by GPO. Please let us know if you encounter any other issues. 

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s801.xml
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s802.xml
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s803.xml
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s804.xml
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s805.xml
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s806.xml
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/sres/BILLSTATUS-115sres108.xml
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr1848.xml
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr1849.xml

**Comment by anerbovig** [comment]
Great, thank you!
