### ISSUE TITLE
missing titles in bill status xml this morning

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#53]
New bills this morning did not have title metadata,  For example:

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr1864.xml

Titles are now available on congress.gov and I assume they will be filtering into the feed with the next update.   Was this a one-off consequence of reprocessing/release or can we expect status information about bills before they get title metadata regularly.

**Comment by 104PL104** [comment]
This was a one-off. You should expect title and bill number data first. Often status metadata will be available at the same time, but if it arrives first that's an indication of a processing issue.

**Comment by llaplant** [comment]
Verified titles are available.
