### ISSUE TITLE
Cosponsor issues for several bills

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#54]
Hi, the issue that I reported in https://github.com/usgpo/bill-status/issues/50 is happening again for the following bills, with no cosponsors listed on the cosponsor tab on Congress.gov:

S. 774
S. 751
S. 681
S. 792
S. 796
S. 751
S. 733
S. 692
S. 655
S. 616
S. 623
S. 544
S. 382
S. 178

**Comment by 104PL104** [comment]
Investigating. Thank you for reporting this.

**Comment by llaplant** [comment]
https://www.congress.gov/bill/115th-congress/senate-bill/774/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/751/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/761/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/792/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/796/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/751/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/733/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/692/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/655/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/616/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/623/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/544/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/382/cosponsors
https://www.congress.gov/bill/115th-congress/senate-bill/178/cosponsors
