### ISSUE TITLE
Field name recommendations

### ISSUE THREAD

**Issue by konklone** [usgpo/bill-status#56]
From https://www.govinfo.gov/bulkdata/json/BILLSTATUS/115/s -

```json
{
"mimeType": "application/xml",
"size": "17.4 kB",
"lastModifiedTime": 1491269941000,
"fullFileName": "BILLSTATUS-115s17.xml",
"name": "BILLSTATUS-115s17.xml",
"fmtLastModified": "04-Apr-2017 01:39",
"folder": false,
"displayLable": "BILLSTATUS-115s17.xml",
"cfrTitle": 0,
"justFileName": "BILLSTATUS-115s17.xml",
"fileExtention": "xml"
}
```

I have a few recommendations:

* Spelling fields out entirely instead of using abbreviations. So `fmtLastModified` would better be represented as `formattedLastModified` or `lastModifiedFormatted` -- or, to be consistent with the `lastModifiedTime` field, `formattedLastModifiedTime` or `lastModifiedTimeFormatted`. This avoids ambiguity and keeps things consistent.
* Making the `size` field an integer containing the number of bytes, instead of a text field like "17.4 kB". That will require an unnecessary amount of text parsing, and also drops information (is it **exactly** 17.4 kB? It's probably being rounded). This is similar to the approach taken for `lastModifiedTime`.

**Comment by jonquandt** [comment]
Thanks for the feedback! - Scheduled for our next release, and we'll let you know when it's available.

**Comment by jonquandt** [comment]
This is resolved and available. 

```
{
"mimeType": "application/xml",
"size": 18071,
"formattedLastModifiedTime": "19-Jun-2017 11:48",
"fullFileName": "BILLSTATUS-115s17.xml",
"name": "BILLSTATUS-115s17.xml",
"folder": false,
"displayLabel": "BILLSTATUS-115s17.xml",
"formattedSize": "17.6 kB",
"justFileName": "BILLSTATUS-115s17.xml",
"fileExtention": "xml"
},
```

**Comment by konklone** [comment]
Thank you! 😺
