### ISSUE TITLE
Provide direct URLs to files as part of the bulk data feed

### ISSUE THREAD

**Issue by konklone** [usgpo/bill-status#57]
Looking at https://www.govinfo.gov/bulkdata/json/BILLSTATUS/115/s and https://www.govinfo.gov/bulkdata/json/BILLS/115/1, the data objects don't include URLs, so users are forced to construct those URLs from those constituent parts. 

Here's the data for S. 11:

```json
{
"mimeType": "application/xml",
"size": "8 kB",
"lastModifiedTime": 1483595306000,
"fullFileName": "BILLS-115s11is.xml",
"name": "BILLS-115s11is.xml",
"fmtLastModified": "05-Jan-2017 05:48",
"folder": false,
"displayLable": "BILLS-115s11is.xml",
"cfrTitle": 0,
"justFileName": "BILLS-115s11is.xml",
"fileExtention": "xml"
}
```

As best I can tell, the relevant URLs are here:

* https://www.govinfo.gov/content/pkg/BILLS-115s11is/pdf/BILLS-115s11is.pdf
* https://www.govinfo.gov/app/details/BILLS-115s11is/

At the very least, you have to remove .xml and then guess that adding .pdf will do it. But I think including URLs directly would be easier on implementers and remove ambiguity.

**Comment by jonquandt** [comment]
@konklone  -- Thanks for pointing this out! This is scheduled for our next release. For future general **govinfo** bulk data issues, please use the [bulk-data](https://github.com/usgpo/bulk-data/issues) repo.

I didn't have a chance to update the repo before @llaplant's presentation, but the readme includes the links now.

**Comment by jonquandt** [comment]
@konklone  -- we're scheduling this one into our next release now - work on RSS and sitemaps prevented this one from making it.

In the mean time, you may want to look at our new RSS implementation for bulk data and our regular collections (see www.govinfo.gov/feeds), which may help provide some of the information you're looking for. It's a starting point for now; we're interested in feedback, and I'll be creating a separate repo for it in the next week or so. 

We're also working on migrating the existing FDsys sitemaps information for **govinfo**. That should be coming soon, and I'll let you know when it's available here as well.

**Comment by jonquandt** [comment]
@konklone -- this has been updated in our production environment. Let me know if you see any issues, and we can reopen or create a new issue as needed. 

https://www.govinfo.gov/bulkdata/json/BILLSTATUS/115/

```json
{
"formattedLastModifiedTime": "14-Sep-2017 03:42",
"name": "sconres",
"folder": true,
"displayLabel": "sconres",
"link": "http://www.govinfo.gov/bulkdata/json/BILLS/115/1/sconres",
"justFileName": "sconres"
},
```

**Comment by konklone** [comment]
Thank you!
