### ISSUE TITLE
Bills introduced on 3/28 and 3/29 don't have XML files on bill pages

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#58]
Hi, the bill pages on congress.gov for bills that were introduced on 3/28 and 3/29 only have the .txt and .pdf files for the bill text. Could you please investigate why the XML/HTML files are missing and add them as bill text file versions? Here's an example: https://www.congress.gov/bill/115th-congress/house-bill/1792/text?q=%7B%22search%22%3A%5B%22hr1792%22%5D%7D&r=1

Thank you.

**Comment by anerbovig** [comment]
This is happening for a few scattered bills introduced later as well, like H.R. 1861 (introduced 4/3/17): https://www.congress.gov/bill/115th-congress/house-bill/1861/text?q=%7B%22search%22%3A%5B%22hr1861%22%5D%7D&r=1

**Comment by llaplant** [comment]
XML is available. Thanks!
