### ISSUE TITLE
A couple of minor issues

### ISSUE THREAD

**Issue by amarnathm** [usgpo/bill-status#59]
A couple of minor issues.

In  BILLSTATUS-114hr240.xml, Senate Recorded Vote 57 appears twice with slightly different text.

The corresponding bill on congress.gov shows the same for Recorded Vote 57 -- it appears twice.
https://www.congress.gov/bill/114th-congress/house-bill/240/all-actions?overview=closed&q=%7B%22roll-call-vote%22%3A%22all%22%7D

Are these the same vote inadvertently recorded twice? 

There are a few other bills that have this (minor) issue.

----

In BILLSTATUS-114hres144.xml, there is an invisible character before the xml tag. It's not visible in a number of text editors, but "less filename" on a linux terminal will show it.  It's similar to:

foo&lt;?xml version="1.0" encoding="utf-8"?&gt;

A workaround for developers is as proposed in  http://stackoverflow.com/questions/3030903/content-is-not-allowed-in-prolog-when-parsing-perfectly-valid-xml-on-gae  -- however, it does take a bit of time to figure out that this is the issue.

The same issue is there in several house-roll-call xml files, e.g., http://clerk.house.gov/evs/2003/roll002.xml -- but that's probably outside the scope of this repo.

**Comment by llaplant** [comment]
Thank you for inquiring about this; both actions presented on Congress.gov and the Bulk Data Repository are valid. In addition, thank you for letting us know about the invisible character.
