### ISSUE TITLE
amendments are missing amendedBill fields

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#61]
Several bills have amendments that are missing fields.

https://www.gpo.gov//fdsys/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr5.xml:

````
<amendedBill>
<title>Regulatory Accountability Act of 2017</title>
<originChamber>House</originChamber>
<originChamberCode>H</originChamberCode>
</amendedBill>
````

amendedBill is supposed to contain `congress`, `type`, and `number` fields.

This change has broken the [unitedstates project importer](https://github.com/unitedstates/congress). I am getting frequent requests from journalists for accurate data on enacted laws approaching the President's 100th day, so I'd appreciate an urgent fix. And as I noted in a previous issue, it would be helpful if the XML files were validated prior to publication - such as by using the [unitedstates project importer](https://github.com/unitedstates/congress) so you would know the issues I'm going to report before I report them.

**Comment by llaplant** [comment]
Fixed in https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr5.xml and we are reprocesing other impacted files today. Using your importer as part of our regression testing is on our roadmap.
