### ISSUE TITLE
115hr1228 lost its Signed by President action

### ISSUE THREAD

**Issue by JoshData** [usgpo/bill-status#62]
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr1228.xml
https://www.congress.gov/bill/115th-congress/house-bill/1228/actions

Seems to have had an action for Signed by President previously but doesn't right now - it goes straight from `Became Public Law No: 115-19.` to `Presented to President.`. Congress.gov shows the signed action.

**Comment by llaplant** [comment]
This action is currently not available in the LOC data feed. The Congress.gov and FDsys teams are taking a look.

**Comment by JoshData** [comment]
Thanks. 

On May 4, 2017 9:30:27 AM EDT, Lisa LaPlant <notifications@github.com> wrote:
>This action is currently not available in the LOC data feed. The
>Congress.gov and FDsys teams are taking a look. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/usgpo/bill-status/issues/62#issuecomment-299185334

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by llaplant** [comment]
Updated
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr1228.xml

**Comment by JoshData** [comment]
Thanks! (And phew, I thought maybe the President forgot to sign it. :) )
