### ISSUE TITLE
link to cq.com marku report  in congress.gov action

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#63]
https://www.congress.gov/bill/115th-congress/house-bill/255/all-actions-without-amendments?

01/24/2017	Senate	Committee on Commerce, Science, and Transportation. Ordered to be reported without amendment favorably. Markup report CQ 

I assume this is something stray and not intentional?

**Comment by 104PL104** [comment]
Correct. This is not intentional.

**Comment by llaplant** [comment]
Resolved
https://www.congress.gov/bill/115th-congress/house-bill/255/all-actions-without-amendments
