### ISSUE TITLE
Bills with Duplicate Cosponsors

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#64]
Hi, there are a few bills that had cosponsors added yesterday display the same senator multiple times on the cosponsor tab:

- S. 926: https://www.congress.gov/bill/115th-congress/senate-bill/926/cosponsors?q=%7B%22search%22%3A%5B%22s926%22%5D%7D&r=1&overview=closed#tabs
- S. 765:  https://www.congress.gov/bill/115th-congress/senate-bill/765/cosponsors?q=%7B%22search%22%3A%5B%22s765%22%5D%7D&r=1&overview=closed#tabs
- S. 798: https://www.congress.gov/bill/115th-congress/senate-bill/978/cosponsors?q=%7B%22search%22%3A%5B%22s978%22%5D%7D&r=1
- S. 1034: https://www.congress.gov/bill/115th-congress/senate-bill/1034/cosponsors?q=%7B%22search%22%3A%5B%22s1034%22%5D%7D&r=1&overview=closed#tabs
- S. 838: https://www.congress.gov/bill/115th-congress/senate-bill/838/cosponsors?q=%7B%22search%22%3A%5B%22s838%22%5D%7D&r=1&overview=closed#tabs
- S. 992: https://www.congress.gov/bill/115th-congress/senate-bill/992/cosponsors?q=%7B%22search%22%3A%5B%22s992%22%5D%7D&r=1&overview=closed#tabs

**Comment by llaplant** [comment]
@104PL104 this appears to be resolved. Could you take a look and close if it is good to go?
