### ISSUE TITLE
Public Law Text File is Cut Off (P.L. 114-328)

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#65]
Hi there, the text file for the 2017 NDAA from the 114th Congress is cut off before the end of the actual text:

https://www.gpo.gov/fdsys/pkg/PLAW-114publ328/html/PLAW-114publ328.htm

Could this be fixed to reflect the full text of the law? Thanks!

**Comment by llaplant** [comment]
Fixed!
https://www.gpo.gov/fdsys/pkg/PLAW-114publ328/html/PLAW-114publ328.htm

**Comment by anerbovig** [comment]
Thank you!
