### ISSUE TITLE
Incorrect Nomination Information (PN562)

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#66]
Hello, I'm not sure if this is the correct place to raise this issue but there's incorrect information on the nomination page for David Wright (PN 562): https://www.congress.gov/nomination/115th-congress/562

Jeffery Baran has not resigned from the NRC, according to their press office.

If there's somewhere else I should submit this issue please let me know. Thank you!

**Comment by llaplant** [comment]
Issue sent to the Congress.gov team. Closing issue in Bill Status repository.
