### ISSUE TITLE
missing BILLSTATUS-115s1706.xml and BILLSTATUS-115s1707.xml

### ISSUE THREAD

**Issue by AllenChu** [usgpo/bill-status#68]
those two bills are available on congress.gov but not at fdsys.
thanks.

**Comment by llaplant** [comment]
Files are now available. 

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1706.xml
https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1707.xml
