### ISSUE TITLE
Bill cosponsors - possible to add separate elements for party, state and district?

### ISSUE THREAD

**Issue by dwillis** [usgpo/bill-status#7]
Bill cosponsors listed in bill status files [like this one](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr4570.xml) have the cosponsor's state, party and district inside a single attribute: 
![screen shot 2016-04-21 at 4 53 18 pm](https://cloud.githubusercontent.com/assets/2214/14723961/9520e782-07e1-11e6-8d73-5b0d1b373c4f.png)

Would it be possible to have separate attributes for each? Thanks!

**Comment by llaplant** [comment]
For sample files see  [BILLSTATUS-114s469.xml](../blob/master/BILLSTATUS-114s469.xml) and [BILLSTATUS-114hr2566.xml](../blob/master/BILLSTATUS-114hr2566.xml). For more information see [changelog.md](../blob/master/CHANGELOG.md). Planned deployment to Production in November.

**Comment by dwillis** [comment]
Excellent, thanks! Is there a way to know the day this is deployed?

**Comment by llaplant** [comment]
Yes. We'll update here and in the change log when we know the date of the deployment. The new fields will be be visible in day forward data first, and it will take us a day or so to reprocess older data.

**Comment by dwillis** [comment]
Many thanks.

**Comment by 104PL104** [comment]
We plan to deploy this this in the first week of November 2016. Expect a more precise estimate next week.

**Comment by llaplant** [comment]
Deployment on November 3rd and we will reprocess data after the deployment!

**Comment by dwillis** [comment]
Thanks! It looks like not all bills have been reprocessed - can you provide an update on that?

**Comment by llaplant** [comment]
The Library and GPO are working together to reprocess the remaining >400 bill status files that were not reprocessed successfully.

**Comment by llaplant** [comment]
This is available in Production for 114th forward, but 113th still needs to be reprocessed. Reprocessing the 113th will most likely happen when Congress is not in session. I'll update here when we have a date. Keeping issue open but removing upcoming release label.

**Comment by llaplant** [comment]
Reprocessed 113th Congress.
