### ISSUE TITLE
Bill Status of 09/26 Introduced Bills

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#71]
Hello, all of the pages for bills and resolutions introduced in the House/Senate yesterday are up on Congress.gov, I see the text in the bulk data repository but none of the measures introduced yesterday have been added to the bill status repository. Is there any reason for the delay in the bulk data store when the information is available elsewhere? Thanks for the clarification!

**Comment by llaplant** [comment]
Checking on it now. May be an earlier job that is taking longer to complete processing due to a large number of adds or updates.

**Comment by anerbovig** [comment]
Thank you!

**Comment by llaplant** [comment]
Two bill status files, BILLSTATUS-115hr2810 and BILLSTATUS-115hr3354, are taking more time than usual to process because of their size. Other updated files are available.
