### ISSUE TITLE
Bill Status Updates for 9/28, 9/29

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#72]
Hi there, 

No new bill status updates have come through for bill actions from yesterday, similar to earlier this week in https://github.com/usgpo/bill-status/issues/71

For example, I'm missing bill actions from 9/28 and 9/29 for S. 1866, but I can see them on the Congress.gov bill page even though the last bulk data file for that bill in the repository only has the Senate action from 9/26:

Congress.gov page: https://www.congress.gov/bill/115th-congress/senate-bill/1866/actions?q=%7B%22search%22%3A%5B%22s1866%22%5D%7D&r=1
Bill Status file as of 28-Sept-2017 07:58: https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1866.xml

Is there somewhere I should be looking for bill actions outside of the bill status files in the bulk data to stay up to date when there's a bit of a delay? Thank you!

**Comment by wcarter** [comment]
Are the consistent delays in bill status xml recently a reflection of a change in process?  Would you appreciate an issue to always be opened when the user community notices that there is content on congress.gov that is not included in the next bill status update?

**Comment by jonquandt** [comment]
@anerbovig - It looks like the 115th Congress bill status job got stuck in processing last night. We're looking into why our internal alert didn't notify us of the issue. 

We've kicked the job off again and the billstatus  above is updated to include the latest action as:

```xml
<latestAction>
<text>Presented to President.</text>
<actionDate>2017-09-29</actionDate>
<links/>
</latestAction>
```

**Comment by jonquandt** [comment]
@wcarter - yes, creating a new issue is fine. This was a different issue than #71

**Comment by jonquandt** [comment]
An additional ~370 bills have gone through for the 115th congress, so I think we can close this out.

We have something new coming that should help provide more timely updates when a job is run.

**Comment by anerbovig** [comment]
Thanks again!

**Comment by wcarter** [comment]
@jonquandt roughly when is that something new going to be implemented?

**Comment by jonquandt** [comment]
Now!

Here is an RSS feed that will provide notifications when a batch job completes. It also includes a list of bill status files that were updated as part of the batch.

About to update the readme with this info.

https://www.govinfo.gov/rss/billstatus-batch.xml
