### ISSUE TITLE
Missing Bill Text for H.R. 3990

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#73]
Hi there, I see on the Congress.gov page for H.R. 3990, the text tab includes a (1) but there isn't any text listed: https://www.congress.gov/bill/115th-congress/house-bill/3990/text

It's been available in the FDsys repository for a few days: https://www.gpo.gov/fdsys/bulkdata/BILLS/115/1/hr

Do you know when this will carry through to the Congress.gov bill page? Thanks!

**Comment by 104PL104** [comment]
Thank you for reporting this. We'll ingest the text ASAP. Should be resolved today.

**Comment by 104PL104** [comment]
Text is now at https://www.congress.gov/bill/115th-congress/house-bill/3990/text/ih, and should flow through to Bulk Data soon.

**Comment by anerbovig** [comment]
Thank you!
