### ISSUE TITLE
New introduced bill on congress.gov but not in latest bill status update

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#74]
HR 4076 is on congress.gov
https://www.congress.gov/bill/115th-congress/house-bill/4076?

But is not in the latest batch listed here:  https://www.govinfo.gov/rss/billstatus-batch.xml

BILLSTATUS batch update complete Tue, 17 Oct 2017 11:17:00 -0400

And I don't see any of these updates reflected in the sitemap:

https://www.gpo.gov/smap/bulkdata/BILLSTATUS/115hr/sitemap.xml

**Comment by llaplant** [comment]
Updated
