### ISSUE TITLE
no new bill status content today

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#75]
Looking at  https://www.govinfo.gov/rss/billstatus-batch.xml   there has been no new bill status content today, though there are new bills are on congress.gov  -- for example hr 4089 

https://www.congress.gov/bill/115th-congress/house-bill/4089

<item>
<guid isPermaLink="false">BILLSTATUS-2017-10-20T00:40:44Z</guid>
<title>
BILLSTATUS batch update complete Thu, 19 Oct 2017 20:41:00 -0400
</title>
<pubDate>Thu, 19 Oct 2017 20:41:00 -0400</pubDate>
<description><a href=></a><br/></description>
</item>

**Comment by jonquandt** [comment]
Looking into it - thanks.

**Comment by jonquandt** [comment]
This has been resolved. We paused the job to do some patching and it looks like it failed to startup during the service restart.
