### ISSUE TITLE
No new bill status content today

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#76]
Looking at https://www.govinfo.gov/rss/billstatus-batch.xml there has been no new bill status content today, though there are new bills are on congress.gov -- for example s 2032

https://www.congress.gov/bill/115th-congress/senate-bill/2032?

Most recent entry:

<item>
<guid isPermaLink="false">BILLSTATUS-2017-10-30T16:52:42Z</guid>
<title>
BILLSTATUS batch update complete Mon, 30 Oct 2017 12:53:00 -0400
</title>
<pubDate>Mon, 30 Oct 2017 12:53:00 -0400</pubDate>

**Comment by llaplant** [comment]
There was an issue with the batch from last night that had to be resolved. 

This just finished: 

Batch 10/30/2017 19:38:37 completed processing and publishing Tue Oct 31 13:11:58 UTC 2017

https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1689.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1282.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s2001.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr4129.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr4136.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s46.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1917.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr1886.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr613.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1084.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s573.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1994.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/sres/BILLSTATUS-115sres297.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr2266.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1237.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hconres/BILLSTATUS-115hconres71.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr3921.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr2521.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr1223.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr1585.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr3849.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr3534.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr3876.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr3889.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1885.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr3882.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1872.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1883.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr3692.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s504.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr4010.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr3832.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr3991.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hres/BILLSTATUS-115hres359.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hres/BILLSTATUS-115hres590.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr4097.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s1997.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hjres/BILLSTATUS-115hjres111.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hres/BILLSTATUS-115hres446.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr2989.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr4117.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/sres/BILLSTATUS-115sres147.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr4122.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/s/BILLSTATUS-115s2006.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/sres/BILLSTATUS-115sres309.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/sres/BILLSTATUS-115sres303.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/hres/BILLSTATUS-115hres593.xml
https://www.govinfo.gov/bulkdata/BILLSTATUS/115/sres/BILLSTATUS-115sres310.xml
 
The following are currently processing. S. 2032 is in the batch that is currently processing. 

UPDATE: BILLSTATUS-115s1282  2017-10-30T19:45:12Z
UPDATE: BILLSTATUS-115hr2521  2017-10-30T19:45:13Z
UPDATE: BILLSTATUS-115hr2921  2017-10-30T19:45:13Z
UPDATE: BILLSTATUS-115hres460  2017-10-30T20:00:11Z
UPDATE: BILLSTATUS-115hres466  2017-10-30T20:00:12Z
UPDATE: BILLSTATUS-115hres461  2017-10-30T20:00:12Z
UPDATE: BILLSTATUS-115hr2941  2017-10-30T20:00:13Z
UPDATE: BILLSTATUS-115hr3567  2017-10-30T20:00:13Z
UPDATE: BILLSTATUS-115hr4132  2017-10-30T20:15:12Z
UPDATE: BILLSTATUS-115hres467  2017-10-30T20:30:11Z
UPDATE: BILLSTATUS-115hr2727  2017-10-30T20:30:11Z
UPDATE: BILLSTATUS-115s1952  2017-10-30T20:30:12Z
UPDATE: BILLSTATUS-115hr3898  2017-10-30T20:45:11Z
UPDATE: BILLSTATUS-115hres569  2017-10-30T20:45:11Z
UPDATE: BILLSTATUS-115hres449  2017-10-30T20:45:11Z
UPDATE: BILLSTATUS-115s1941  2017-10-30T20:45:12Z
UPDATE: BILLSTATUS-115hr4120  2017-10-30T21:15:11Z
UPDATE: BILLSTATUS-115hconres85  2017-10-30T21:30:11Z
UPDATE: BILLSTATUS-115hr3883  2017-10-30T21:30:12Z
UPDATE: BILLSTATUS-115hres470  2017-10-30T21:45:11Z
UPDATE: BILLSTATUS-115hres471  2017-10-30T21:45:11Z
UPDATE: BILLSTATUS-115hr1355  2017-10-30T21:45:11Z
UPDATE: BILLSTATUS-115sres228  2017-10-30T21:45:12Z
UPDATE: BILLSTATUS-115hr3114  2017-10-30T22:00:11Z
UPDATE: BILLSTATUS-115hres456  2017-10-30T22:00:11Z
UPDATE: BILLSTATUS-115hr3436  2017-10-30T22:15:11Z
UPDATE: BILLSTATUS-115s1438  2017-10-30T22:15:11Z
UPDATE: BILLSTATUS-115hr3058  2017-10-30T22:15:11Z
UPDATE: BILLSTATUS-115hr2630  2017-10-30T22:15:11Z
UPDATE: BILLSTATUS-115s1222  2017-10-30T22:15:11Z
UPDATE: BILLSTATUS-115s585  2017-10-31T04:28:29Z
UPDATE: BILLSTATUS-115s1766  2017-10-31T04:30:32Z
UPDATE: BILLSTATUS-115hr238  2017-10-31T04:31:15Z
UPDATE: BILLSTATUS-115hr2142  2017-10-31T04:31:16Z
UPDATE: BILLSTATUS-115hr2105  2017-10-31T04:31:16Z
UPDATE: BILLSTATUS-115hr3101  2017-10-31T04:31:16Z
UPDATE: BILLSTATUS-115hr1918  2017-10-31T04:31:16Z
UPDATE: BILLSTATUS-115hr4010  2017-10-31T04:31:17Z
UPDATE: BILLSTATUS-115sres294  2017-10-31T04:31:18Z
UPDATE: BILLSTATUS-115sres299  2017-10-31T04:31:18Z
UPDATE: BILLSTATUS-115sres284  2017-10-31T04:31:18Z
UPDATE: BILLSTATUS-115s226  2017-10-31T04:31:51Z
UPDATE: BILLSTATUS-115s96  2017-10-31T04:31:51Z
UPDATE: BILLSTATUS-115s298  2017-10-31T04:31:52Z
UPDATE: BILLSTATUS-115s589  2017-10-31T04:31:53Z
UPDATE: BILLSTATUS-115s1007  2017-10-31T04:31:54Z
UPDATE: BILLSTATUS-115s992  2017-10-31T04:31:54Z
UPDATE: BILLSTATUS-115s721  2017-10-31T04:31:54Z
UPDATE: BILLSTATUS-115s972  2017-10-31T04:31:54Z
UPDATE: BILLSTATUS-115s1069  2017-10-31T04:31:55Z
UPDATE: BILLSTATUS-115s1070  2017-10-31T04:31:55Z
UPDATE: BILLSTATUS-115s1072  2017-10-31T04:31:55Z
UPDATE: BILLSTATUS-115s1075  2017-10-31T04:31:55Z
UPDATE: BILLSTATUS-115s1074  2017-10-31T04:31:55Z
UPDATE: BILLSTATUS-115s1652  2017-10-31T04:31:56Z
UPDATE: BILLSTATUS-115s1580  2017-10-31T04:31:56Z
UPDATE: BILLSTATUS-115s1815  2017-10-31T04:31:56Z
UPDATE: BILLSTATUS-115s1668  2017-10-31T04:31:56Z
UPDATE: BILLSTATUS-115s1682  2017-10-31T04:31:56Z
UPDATE: BILLSTATUS-115s1951  2017-10-31T04:31:56Z
UPDATE: BILLSTATUS-115s1564  2017-10-31T04:31:56Z
UPDATE: BILLSTATUS-115s1687  2017-10-31T04:31:56Z
UPDATE: BILLSTATUS-115s1996  2017-10-31T04:31:57Z
UPDATE: BILLSTATUS-115s1979  2017-10-31T04:31:57Z
UPDATE: BILLSTATUS-115s2000  2017-10-31T04:31:59Z
UPDATE: BILLSTATUS-115s1998  2017-10-31T04:31:59Z
UPDATE: BILLSTATUS-115s1199  2017-10-31T04:32:33Z
UPDATE: BILLSTATUS-115hr1698  2017-10-31T04:32:33Z
NEW:      BILLSTATUS-115s2031  2017-10-31T04:32:33Z
NEW:      BILLSTATUS-115s2030  2017-10-31T04:32:33Z
NEW:      BILLSTATUS-115s2032  2017-10-31T04:32:34Z
UPDATE: BILLSTATUS-115s793  2017-10-31T04:32:57Z
UPDATE: BILLSTATUS-115s1690  2017-10-31T04:33:53Z
UPDATE: BILLSTATUS-115s322  2017-10-31T04:37:17Z
UPDATE: BILLSTATUS-115s1674  2017-10-31T04:38:07Z
UPDATE: BILLSTATUS-115s1022  2017-10-31T04:38:29Z
UPDATE: BILLSTATUS-115s253  2017-10-31T04:43:30Z
UPDATE: BILLSTATUS-115s445  2017-10-31T04:48:58Z
UPDATE: BILLSTATUS-115s872  2017-10-31T04:50:58Z
UPDATE: BILLSTATUS-115s1953  2017-10-31T04:51:14Z
UPDATE: BILLSTATUS-115s1859  2017-10-31T04:52:54Z
UPDATE: BILLSTATUS-115s1981  2017-10-31T04:52:59Z
UPDATE: BILLSTATUS-115s978  2017-10-31T04:53:20Z
UPDATE: BILLSTATUS-115s629  2017-10-31T04:53:42Z
UPDATE: BILLSTATUS-115s1842  2017-10-31T04:54:39Z
UPDATE: BILLSTATUS-115s324  2017-10-31T05:00:00Z
UPDATE: BILLSTATUS-115s2009  2017-10-31T05:00:11Z
UPDATE: BILLSTATUS-115s2008  2017-10-31T05:00:18Z
UPDATE: BILLSTATUS-115s2013  2017-10-31T05:00:18Z
UPDATE: BILLSTATUS-115s2011  2017-10-31T05:00:18Z
UPDATE: BILLSTATUS-115s2014  2017-10-31T05:00:19Z
UPDATE: BILLSTATUS-115hr4164  2017-10-31T05:00:19Z
UPDATE: BILLSTATUS-115s2004  2017-10-31T05:00:19Z
UPDATE: BILLSTATUS-115hr4162  2017-10-31T05:00:19Z
UPDATE: BILLSTATUS-115s1343  2017-10-31T05:01:41Z
UPDATE: BILLSTATUS-115s674  2017-10-31T05:01:52Z
UPDATE: BILLSTATUS-115s1738  2017-10-31T05:04:12Z
UPDATE: BILLSTATUS-115s1827  2017-10-31T05:06:32Z
UPDATE: BILLSTATUS-115s700  2017-10-31T05:07:07Z
UPDATE: BILLSTATUS-115s266  2017-10-31T05:25:14Z
UPDATE: BILLSTATUS-115s2019  2017-10-31T05:25:34Z
UPDATE: BILLSTATUS-115s353  2017-10-31T05:25:44Z
UPDATE: BILLSTATUS-115s1746  2017-10-31T05:29:10Z
UPDATE: BILLSTATUS-115sres250  2017-10-31T05:35:18Z
UPDATE: BILLSTATUS-115s503  2017-10-31T05:36:14Z
UPDATE: BILLSTATUS-115s339  2017-10-31T05:45:27Z
UPDATE: BILLSTATUS-115s1064  2017-10-31T05:46:41Z
UPDATE: BILLSTATUS-115s654  2017-10-31T05:51:48Z
UPDATE: BILLSTATUS-115hr4102  2017-10-31T07:12:16Z
UPDATE: BILLSTATUS-115hr4032  2017-10-31T07:12:16Z
UPDATE: BILLSTATUS-115hr4074  2017-10-31T07:12:16Z
UPDATE: BILLSTATUS-115hr4114  2017-10-31T07:12:17Z
UPDATE: BILLSTATUS-115hr4151  2017-10-31T09:15:11Z
UPDATE: BILLSTATUS-115hr2823  2017-10-31T10:26:10Z
UPDATE: BILLSTATUS-115hjres88  2017-10-31T10:26:10Z
UPDATE: BILLSTATUS-115hr4154  2017-10-31T11:15:11Z
UPDATE: BILLSTATUS-115hr4155  2017-10-31T11:15:11Z
UPDATE: BILLSTATUS-115hr4157  2017-10-31T11:15:11Z
UPDATE: BILLSTATUS-115hr4156  2017-10-31T11:15:11Z
UPDATE: BILLSTATUS-115hr4159  2017-10-31T11:15:11Z
UPDATE: BILLSTATUS-115hr4152  2017-10-31T11:15:11Z
UPDATE: BILLSTATUS-115hr4124  2017-10-31T12:15:11Z
UPDATE: BILLSTATUS-115s234  2017-10-31T12:15:15Z
UPDATE: BILLSTATUS-115hr4133  2017-10-31T12:30:11Z
UPDATE: BILLSTATUS-115hr4138  2017-10-31T12:30:12Z
UPDATE: BILLSTATUS-115hr4134  2017-10-31T12:30:12Z
UPDATE: BILLSTATUS-115hr4139  2017-10-31T12:30:12Z
UPDATE: BILLSTATUS-115hr4158  2017-10-31T12:30:13Z
UPDATE: BILLSTATUS-115hr4118  2017-10-31T12:30:14Z
UPDATE: BILLSTATUS-115hr4135  2017-10-31T12:30:14Z
NEW:      BILLSTATUS-115sres312  2017-10-31T12:42:12Z
UPDATE: BILLSTATUS-115sres211  2017-10-31T12:42:12Z
UPDATE: BILLSTATUS-115sres75  2017-10-31T12:42:12Z
NEW:      BILLSTATUS-115sres313  2017-10-31T12:42:12Z
NEW:      BILLSTATUS-115sres314  2017-10-31T12:42:13Z
UPDATE: BILLSTATUS-115hr4140  2017-10-31T12:45:11Z
UPDATE: BILLSTATUS-115hr4141  2017-10-31T12:45:11Z
UPDATE: BILLSTATUS-115s2012  2017-10-31T12:45:12Z
UPDATE: BILLSTATUS-115hr4142  2017-10-31T13:00:16Z
UPDATE: BILLSTATUS-115hr4143  2017-10-31T13:00:16Z
UPDATE: BILLSTATUS-115hr4144  2017-10-31T13:00:16Z
UPDATE: BILLSTATUS-115hr4145  2017-10-31T13:00:17Z
UPDATE: BILLSTATUS-115hr760  2017-10-31T13:12:14Z
UPDATE: BILLSTATUS-115hr4150  2017-10-31T13:15:11Z
UPDATE: BILLSTATUS-115hr4146  2017-10-31T13:15:11Z
UPDATE: BILLSTATUS-115s2004  2017-10-31T05:00:19Z
UPDATE: BILLSTATUS-115s2005  2017-10-31T13:15:12Z
UPDATE: BILLSTATUS-115s2007  2017-10-31T13:15:12Z

**Comment by wcarter** [comment]
Thanks!
