### ISSUE TITLE
New introduced bills on congress.gov but not in latest bill status update

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#77]
Yesterday's introduced bills are not yet included in the latest batch listed here:
https://www.govinfo.gov/rss/billstatus-batch.xml

BILLSTATUS batch update complete Fri, 03 Nov 2017 07:33:00 -0400
Friday, November 3, 2017, 7:33 AM

HR 4235 is on congress.gov
https://www.congress.gov/bill/115th-congress/house-bill/4235

S 2074
https://www.congress.gov/bill/115th-congress/senate-bill/2074

**Comment by llaplant** [comment]
They were processed around 8:30 this morning.

**Comment by kboyd35** [comment]
Thanks!
