### ISSUE TITLE
New introduced bills on congress.gov but not in latest bill status update

### ISSUE THREAD

**Issue by kboyd35** [usgpo/bill-status#78]
Yesterday's introduced house bills and resolutions are not yet included in the latest batch listed here:
https://www.govinfo.gov/rss/billstatus-batch.xml

BILLSTATUS batch update complete Wed, 15 Nov 2017 02:50:00 -0500
Wednesday, November 15, 2017, 2:50 AM

HR 4382 through HR 4394 are on congress.gov
https://www.congress.gov/bill/115th-congress/house-bill/4394

HRES 619 and HRES 620 are on congress.gov
https://www.congress.gov/bill/115th-congress/house-resolution/620

**Comment by llaplant** [comment]
Morning! There were 189 newly added or updated files processing. They are publishing to the public site now.
