### ISSUE TITLE
bills available on congress.gov not included in bill status feed

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#79]
HR 4454 through 4457 have been available on congress.gov since midday 11/22/2017 but are not yet available in the bill status feed.

https://www.govinfo.gov/rss/billstatus-batch.xml last batch update is:

<pubDate>Wed, 22 Nov 2017 10:17:00 -0500</pubDate>

However, https://www.gpo.gov/smap/bulkdata/BILLSTATUS/115hr/sitemap.xml and other sitemap files show later updates.

**Comment by jzheng-gpo** [comment]
They are in queue for processing now.  Will bump up the priority now.

**Comment by jzheng-gpo** [comment]
The four HRs went through now. The latest batch update 11/22/2017 18:04:03 is still going on caused by large amount of updates 1994.

**Comment by jzheng-gpo** [comment]
Showing up on the batch BILLSTATUS batch update complete Wed, 22 Nov 2017 18:47:00 -0500 now.
