### ISSUE TITLE
GPO Ids for members

### ISSUE THREAD

**Issue by dwillis** [usgpo/bill-status#8]
Some members appear to have `gpoId` listed in the bill status XML, but others do not (see, for example, Ryan Zinke in [this bill](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr4570.xml). Is there a reason for this? It's not significant for me, personally, but was curious. Thanks!

**Comment by llaplant** [comment]
There was an attempt to use gpoIDs as control numbers at the beginning of the Congress.gov project (2012). gpoIDs in this dataset are holdovers from that attempt. By 2015 the House, Senate, LOC, and GPO agreed that BioGuide IDs are our standard. We recommend using BioGuide IDs as control numbers for this data set. 
 
Each present and former member of the United States Congress has a unique control number associated with their record in the Biographical Directory of the United States Congress http://bioguide.congress.gov. Member IDs (also known as "BioGuide IDs") are used as metadata within Congress.gov and legislative documents published by the Government Publishing Office.

**Comment by dwillis** [comment]
Great, thanks!
