### ISSUE TITLE
Some Senate votes missing from actions in HR 1

### ISSUE THREAD

**Issue by dwillis** [usgpo/bill-status#81]
There are several Senate votes missing from the [`actions` element for H.R. 1](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr1.xml), the tax overhaul legislation. Currently (8:40 am on 12/2/2017) it has the vote for final passage in the Senate (roll call 303) but not several prior votes, including roll calls 302, 301, 298, 296, 295, 294 and 293.

**Comment by jzheng-gpo** [comment]
Is this line you are looking for? The last update is on 6:43AM. A update has been started manually:
<amendment>
<purpose/>
<description/>
<congress>115</congress>
<latestAction>
<text>
Amendment SA 1852 agreed to in Senate by Yea-Nay Vote. 51 - 50. Record Vote Number: 298.
</text>
<actionDate>2017-12-02</actionDate>
</latestAction>
<type>SAMDT</type>
<createDate>2017-12-02T05:33:39Z</createDate>
<actions>

**Comment by dwillis** [comment]
Thanks @jzheng-gpo! It looks like it's still missing the other roll calls.

**Comment by llaplant** [comment]
@dwillis 293 may not be on Congress.gov yet, but we are doing manual reprocess to pick up any updated data.

https://www.congress.gov/bill/115th-congress/house-bill/1/all-actions?overview=closed&q=%7B%22roll-call-vote%22%3A%22all%22%7D

**Comment by wcarter** [comment]
It looks like some 12/06/2017 conference-related actions were added to HR1 yesterday?  I would appreciate confirmation of this and any available explanation.

**Comment by 104PL104** [comment]
Confirmed. Yes, the data for HR1 was updated yesterday, and is hopefully now complete and correct. 
Explanation. Sorry for not catching this when it was initially reported on 12/2. The data did not process correctly. We just fixed it yesterday.
