### ISSUE TITLE
Public Law Text File is Cut Off (P.L. 115-87)

### ISSUE THREAD

**Issue by AmitElhanan** [usgpo/bill-status#82]
The text for PL 115-87 is cut off on congress.gov (https://www.congress.gov/bill/115th-congress/house-bill/1679/text) and on https://www.gpo.gov/fdsys/pkg/PLAW-115publ87/html/PLAW-115publ87.htm

**Comment by llaplant** [comment]
Fixed on FDsys/govinfo and ready to be reprocessed on Congress.gov. 

https://www.gpo.gov/fdsys/pkg/PLAW-115publ87/html/PLAW-115publ87.htm

https://www.govinfo.gov/content/pkg/PLAW-115publ87/html/PLAW-115publ87.htm

**Comment by AmitElhanan** [comment]
Thank you!
