### ISSUE TITLE
Few bills missing Subjects index/Policy Area information

### ISSUE THREAD

**Issue by AmitElhanan** [usgpo/bill-status#83]
Good morning, 

I've noticed that a few bills are missing their legislative subject terms and/or Policy area.

I've seen this on:
https://www.congress.gov/bill/115th-congress/senate-bill/2172
https://www.congress.gov/bill/115th-congress/senate-bill/2175
https://www.congress.gov/bill/115th-congress/senate-bill/2177
https://www.congress.gov/bill/115th-congress/senate-bill/2179

**Comment by 104PL104** [comment]
Thank you for reporting this. We'll investigate and then will report back.

**Comment by AmitElhanan** [comment]
The four bills I mentioned in my previous comment all seem to have policy areas. Thank you
