### ISSUE TITLE
bills introduced yesterday on congress.gov but not available in bill status field

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#84]
For example, HR 4642-4660.  The last bill status update was over 2 hours ago.

**Comment by jzheng-gpo** [comment]
The update completed minutes ago.

**Comment by jonquandt** [comment]
@wcarter -- I just saw this flow into the batch feed now, and I see those bills are part of the update. Let us know if you see anything else and we'll look into it more.  Thanks!

**Comment by llaplant** [comment]
Job is running normally.
