### ISSUE TITLE
H.R. 3848 (101st Congress) has last action date in 2020

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bill-status#86]
Hi there, H.R. 3848 has a last action date of 05/18/2020: https://www.congress.gov/bill/101st-congress/house-bill/3848/all-actions?q=%7B%22search%22%3A%5B%22H.R.+3848%22%5D%7D&r=1

It looks like a duplicate of the 5/18 action from 1990, could you correct it? Thank you!

**Comment by llaplant** [comment]
Issue sent to the Congress.gov team. Closing issue in Bill Status repository.
