### ISSUE TITLE
"Actions" tab has numbers in parentheses but the actions are then empty.

### ISSUE THREAD

**Issue by AmitElhanan** [usgpo/bill-status#87]
Looking at https://www.congress.gov/bill/115th-congress/house-bill/5011/all-actions - the "Actions" tab says "6" but then the frame itself says "0 results for All Actions". 

I see the same thing for the following documents:

House Bill 5022
House Bill 5024
House Bill 5029
House Bill 5020
House Bill 5027
House Bill 5025
House Bill 5023
House Bill 5019
House Bill 5021
House Bill 5018
House Bill 5028
House Bill 5013
House Bill 5016
House Bill 5014
House Bill 5011
House Bill 5012
House Bill 5017
Senate Bill 2425
Senate Bill 2426
Senate Bill 2429
Senate Bill 2430
Senate Resolution  406

**Comment by 104PL104** [comment]
Thank you for reporting this. We are working to get it corrected ASAP.

**Comment by llaplant** [comment]
Spot checked on the LC’s Congress.gov and at GPO’s Bulk Data Repository. Closing, but please reopen if there are still issues.
