### ISSUE TITLE
Bills introduced yesterday not up yet

### ISSUE THREAD

**Issue by pelzhaus** [usgpo/bill-status#88]
Hi, a number of bills, [S2431](https://www.congress.gov/bill/115th-congress/senate-bill/2431?q=%7B%22search%22%3A%5B%22s+2431%22%5D%7D) and up, were introduced yesterday and are not present in the BillStatus system yet. Looks like there were multiple updates today already.

**Comment by jzheng-gpo** [comment]
The refreshing job is still running and will complete in next hour.

**Comment by jzheng-gpo** [comment]
Updated to 2450 now.

**Comment by pelzhaus** [comment]
Wonderful thank you!
