### ISSUE TITLE
Introduced Senate Bills and Resolutions missing sponsor metadata

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#89]
Senate Bills and resolutions introduced yesterday do not  have sponsor information on congress.gov or in the bill status xml. For example:

S.2464 — 115th Congress (2017-2018)
A bill to improve border security and to provide conditional provision residence to certain long-term residents who entered the United States as children.
Sponsor: No Sponsor (Introduced 02/27/2018) Cosponsors: (1)
Latest Action: Senate - 02/27/2018 Introduced in the Senate. Read the first time. Placed on Senate Legislative Calendar under Read the First Time. (All Actions)

**Comment by 104PL104** [comment]
Thank you for reporting this. We're working on a fix.

**Comment by 104PL104** [comment]
Data within Congress.gov has been reprocessed. Expect the updates to flow through the the Bulk Data soon. Again, thank you for reporting this.
