### ISSUE TITLE
XML files should be gzipped

### ISSUE THREAD

**Issue by dwillis** [usgpo/bill-status#9]
Gzipping the xml files would greatly speed up the ability to deliver them to clients downloading them. Can this be enabled?

**Comment by JoshData** [comment]
Just to clarify, I think Derek is referring to gzipping transparently at the HTTP level (`Content-Encoding: gzip`), not changing the actual file format of the bill status files. i.e.:

https://en.wikipedia.org/wiki/HTTP_compression

**Comment by llaplant** [comment]
Got it. Thanks!

**Comment by crdunwel** [comment]
Appears this may have been resolved. Thank you! Such a huge bandwidth saver - see below.
![screen shot 2016-05-04 at 4 34 13 pm](https://cloud.githubusercontent.com/assets/942819/15028299/2a3e2db4-1216-11e6-878e-a961c52fb527.png)

**Comment by jonquandt** [comment]
Yep, we enabled it last week. Thanks - @dwillis, let us know if there's anything else you need on this.
