### ISSUE TITLE
introduced bills from 3/22 on congress.gov not available in bill status feed

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#91]
For example HR 5407

https://www.congress.gov/bill/115th-congress/house-bill/5407

**Comment by 104PL104** [comment]
Thank you for reporting. We're investigating.

**Comment by jzheng-gpo** [comment]
The job is running and will update once complete.

**Comment by jzheng-gpo** [comment]
The update is done. And the HR 5407 is in now.

**Comment by wcarter** [comment]
thank you!
