### ISSUE TITLE
XML for H.R. 1625 Engrossed Amendment House/Enrolled

### ISSUE THREAD

**Issue by AmitElhanan** [usgpo/bill-status#93]
I know this is the bill-status repo but I couldn't see another place to put this issue... 

There is no XML yet for these two bill text versions (https://www.congress.gov/bill/115th-congress/house-bill/1625/text/eah? and https://www.congress.gov/bill/115th-congress/house-bill/1625/text/enr?)

**Comment by 104PL104** [comment]
The XML file for H.R. 1625 ENR is now available from FDsys/govinfo:

•	https://www.govinfo.gov/content/pkg/BILLS-115hr1625enr/xml/BILLS-115hr1625enr.xml
•	https://www.gpo.gov/fdsys/pkg/BILLS-115hr1625enr/xml/BILLS-115hr1625enr.xml 

The XML for the ENR of HR1625 has been successfully consumed by Congress.gov, and displays here: https://www.congress.gov/bill/115th-congress/house-bill/1625/text/enr 

We do not yet have closure about the EAH.

**Comment by JoshData** [comment]
Great!

On April 17, 2018 7:48:23 AM EDT, 104PL104 <notifications@github.com> wrote:
>The XML file for H.R. 1625 ENR is now available from FDsys/govinfo:
>
>•	https://www.govinfo.gov/content/pkg/BILLS-115hr1625enr/xml/BILLS-115hr1625enr.xml
>•	https://www.gpo.gov/fdsys/pkg/BILLS-115hr1625enr/xml/BILLS-115hr1625enr.xml
>
>
>The XML for the ENR of HR1625 has been successfully consumed by
>Congress.gov, and displays here:
>https://www.congress.gov/bill/115th-congress/house-bill/1625/text/enr 
>
>We do not yet have closure about the EAH.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/usgpo/bill-status/issues/93#issuecomment-381962570

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
