### ISSUE TITLE
Bill Actio

### ISSUE THREAD

**Issue by mhoward70** [usgpo/bill-status#94]
Hi,

This bill had a hearing on March 7: http://docs.house.gov/Committee/Calendar/ByEvent.aspx?EventID=106943

Could you update the bill status please?

Megan Howard

**Comment by 104PL104** [comment]
Committee hearing data for HR3497 and HR4245 has not yet been received from the official House legislative data systems. We will work with the appropriate offices to resolve this.

**Comment by 104PL104** [comment]
Thank you for reporting this, Megan.

The House sent the data to LOC, and it is available from Congress.gov (links are below. So expect to see it in the Bulk Data soon.

                https://www.congress.gov/bill/115th-congress/house-bill/3497/all-actions

                https://www.congress.gov/bill/115th-congress/house-bill/4245/all-actions
