### ISSUE TITLE
Vote action ambiguity for HR2

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#97]
The latest action for HR 2 is a voice vote in committee however it is not documented as a voice vote:

https://www.congress.gov/bill/115th-congress/house-bill/2?

https://docs.house.gov/meetings/AG/AG00/20180418/108188/CRPT-115-AG00-Vote002-20180418.pdf

Is there some procedural nicety that transformed the vote to a voice vote?

**Comment by 104PL104** [comment]
By the time I was able to look at the latest action for HR2, the action included the text "voice vote." Does the text for the action seem correct to you now?

**Comment by wcarter** [comment]
I phrased my question badly -- the issue was that the action said "voice vote" but the committee documentation recorded the yeas and nays.  The action now correctly says: 

Ordered to be Reported (Amended) by the Yeas and Nays: 26 - 20.
