### ISSUE TITLE
Introduced bills from 5/22 are available on congress.gov but not yet in bill status feed

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#99]
For example:

https://www.congress.gov/bill/115th-congress/house-bill/5923

**Comment by jzheng-gpo** [comment]
There are large amount of bill status under refreshing now and will update you once complete.

**Comment by jzheng-gpo** [comment]
The latest available one is HR 5923 now.

**Comment by kboyd35** [comment]
This is happening again today with bills introduced on 5/23.

For example:
https://www.congress.gov/bill/115th-congress/house-bill/5951

**Comment by jzheng-gpo** [comment]
The congress site is under refresh with new release. The GPO site tries to catch up with large amount of update and this issue could last for couple of days. Those bills are in the queue now. And will update once complete.

**Comment by jzheng-gpo** [comment]
The latest available one is HR 5951 now.
